packages:
  - packages/*
  - plugins/*
  - apps/*

allowBuilds:
  esbuild: true
  workerd: true
  "@parcel/watcher": false
  "@prisma/client": false
  better-sqlite3: true
  dtrace-provider: false

patchedDependencies:
  miniflare@5.20261001.0-alpha: patches/miniflare@5.20261001.0-alpha.patch
