import { existsSync } from "node:fs";
import {
	mkdir,
	readdir,
	readFile,
	rm,
	rmdir,
	writeFile,
} from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import type { PreviewGlobal } from "../types.ts";
import {
	ancestorIds,
	checkVariants,
	fileRouteId,
	isScreen,
	lazyRouteId,
	SCREEN_STATES,
	screenTitle,
} from "./screens.ts";

// The folder at the app root holding one story file per screen. It is no dot
// directory: Storybook's watcher ignores those.
export const STORIES_DIR = "stack-screens";

const STORY_FILE = ".stories.ts";
const ROUTE_FILE = /\.(tsx|ts|jsx|js)$/;
const ROOT_ROUTE = /^__root\./;

const posix = (path: string): string => path.split(sep).join("/");

interface RouteFiles {
	// The root route's files.
	root: string[];
	// The files of each route id: the route's own, and its lazy sibling's.
	byId: Map<string, string[]>;
	// The ids of the routes that are screens.
	screens: string[];
}

// Reads the routes directory: which file declares which route.
async function scanRoutes(routes: string): Promise<RouteFiles> {
	const found: RouteFiles = { root: [], byId: new Map(), screens: [] };
	if (!existsSync(routes)) return found;
	for (const file of (await readdir(routes, { recursive: true })).sort()) {
		if (!ROUTE_FILE.test(file)) continue;
		const path = join(routes, file);
		if (ROOT_ROUTE.test(file)) {
			found.root.push(path);
			continue;
		}
		const source = await readFile(path, "utf8");
		const id = fileRouteId(source);
		const routeId = id ?? lazyRouteId(source);
		if (routeId === null) continue;
		found.byId.set(routeId, [...(found.byId.get(routeId) ?? []), path]);
		if (id !== null && isScreen(id)) found.screens.push(id);
	}
	return found;
}

// A route id's story file, mirroring the id: `/projects/$id` is
// `projects/$id.stories.ts`, an index route (`/projects/`) `projects/index`.
function storyPath(routeId: string): string {
	const path = routeId.slice(1);
	return `${path === "" || path.endsWith("/") ? `${path}index` : path}${STORY_FILE}`;
}

const pascal = (value: string): string =>
	value
		.split(/[^A-Za-z0-9]+/)
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
		.join("");

// One route's CSF file: its title and a story per state, then a hidden story
// per state for every combination of the globals' checked values, which only
// the test run lists (`!dev` leaves the story out of the sidebar and keeps the
// `test` tag). The imports are the screen's graph, as side effects so the
// transform keeps every one: an import of a name nothing uses is dropped.
export function renderStoryFile(
	routeId: string,
	imports: string[],
	globals: PreviewGlobal[],
): string {
	const call = (state: string, chosen?: Record<string, string>): string =>
		`screenStory(${[routeId, state].map((v) => JSON.stringify(v)).join(", ")}${chosen ? `, ${JSON.stringify(chosen)}` : ""})`;
	const variants = checkVariants(globals);
	return [
		"// Generated by `stack screens`, never edited. The imports are this screen's import graph:",
		"// `vitest --changed` follows them to rerun the screen when a file in it changes.",
		'import { screenStory } from "@fcalell/plugin-screens/stories";',
		...imports.map((specifier) => `import ${JSON.stringify(specifier)};`),
		"",
		`export default { title: ${JSON.stringify(screenTitle(routeId))} };`,
		"",
		...SCREEN_STATES.flatMap(({ state, exportName, name }) => [
			`export const ${exportName} = { ...${call(state)}, name: ${JSON.stringify(name)} };`,
			...variants.map(
				({ globals: chosen, label }) =>
					`export const ${exportName}${label.map(pascal).join("")} = { ...${call(state, chosen)}, name: ${JSON.stringify(`${name}, ${label.join(", ")}`)}, tags: ["!dev"] };`,
			),
		]),
		"",
	].join("\n");
}

export interface SyncOptions {
	// The app root, where the stories folder lives.
	root: string;
	// The routes directory, absolute.
	routes: string;
	// The app's fixtures module, absolute; imported once it exists.
	fixtures: string;
	// The toolbar globals the plugins contribute.
	previewGlobals: PreviewGlobal[];
}

// Brings the stories folder to one file per screen: written for a new route,
// rewritten when its content changed, removed for a deleted one and left
// untouched otherwise. A file's content is the route's id and the paths of the
// files its screen imports, so an edit to a route file rewrites nothing.
export async function syncStories(options: SyncOptions): Promise<void> {
	const dir = join(options.root, STORIES_DIR);
	const found = await scanRoutes(options.routes);
	const wanted = new Map<string, string>();
	for (const routeId of found.screens) {
		const file = storyPath(routeId);
		const from = dirname(join(dir, file));
		const imports = [
			...found.root,
			...ancestorIds(routeId).flatMap((id) => found.byId.get(id) ?? []),
			...(found.byId.get(routeId) ?? []),
			...(existsSync(options.fixtures) ? [options.fixtures] : []),
		].map((path) => posix(relative(from, path)));
		wanted.set(file, renderStoryFile(routeId, imports, options.previewGlobals));
	}

	const present = existsSync(dir)
		? (await readdir(dir, { recursive: true }))
				.map(posix)
				.filter((file) => file.endsWith(STORY_FILE))
		: [];
	for (const [file, content] of wanted) {
		const path = join(dir, file);
		if (present.includes(file) && (await readFile(path, "utf8")) === content)
			continue;
		await mkdir(dirname(path), { recursive: true });
		await writeFile(path, content);
	}
	for (const file of present.filter((file) => !wanted.has(file))) {
		await rm(join(dir, file));
		// The folders a route's removal left empty go with it.
		for (let parent = dirname(join(dir, file)); parent !== dir; ) {
			if ((await readdir(parent)).length > 0) break;
			await rmdir(parent);
			parent = dirname(parent);
		}
	}
}
