import { readdirSync } from "node:fs";
import { join } from "node:path";

const GENERATED_HEADER = "// Generated by @fcalell/plugin-node — do not edit.";

// Conventions for the services directory layout (mirrors plugin-api's route
// barrel):
//   - Flat: `src/server/services/<name>.ts` — one service module per name,
//     default-exporting a `defineService(...)`. Subdirectories are ignored.
//   - `index.ts` IS the barrel. Excluded so it doesn't import itself.
//   - `.test.ts` and `.d.ts` files are excluded.
function isServiceFile(file: string): boolean {
	if (!file.endsWith(".ts")) return false;
	if (file.endsWith(".d.ts")) return false;
	if (file.endsWith(".test.ts")) return false;
	if (file === "index.ts") return false;
	return true;
}

function servicesDir(cwd: string): string {
	return join(cwd, "src", "server", "services");
}

// "board-watcher.ts" -> "boardWatcher": a valid import identifier per file.
function identifierFor(file: string): string {
	const base = file.replace(/\.ts$/, "");
	return base.replace(/-([a-z0-9])/g, (_, ch: string) => ch.toUpperCase());
}

// The barrel is tracked in the consumer's tree, not build output under
// `.stack/`, so it must land in the shape the formatter already agrees with
// or every `stack generate` dirties it until the next format pass. Biome
// keeps an array inline while it fits its line width and otherwise breaks it
// one entry per line with a trailing comma; 80 is Biome's default, which
// `@fcalell/biome-config` does not change.
const LINE_WIDTH = 80;

function renderServices(identifiers: string[]): string {
	const inline = `export const services = [${identifiers.join(", ")}];`;
	if (inline.length <= LINE_WIDTH) return inline;
	const lines = identifiers.map((identifier) => `\t${identifier},`).join("\n");
	return `export const services = [\n${lines}\n];`;
}

export function generateServiceBarrel(cwd: string): string {
	let entries: string[];
	try {
		entries = readdirSync(servicesDir(cwd)).filter(isServiceFile).sort();
	} catch {
		entries = [];
	}

	const imports = entries
		.map((file) => {
			const base = file.replace(/\.ts$/, "");
			return `import ${identifierFor(file)} from "./${base}.ts";`;
		})
		.join("\n");
	const services = renderServices(entries.map(identifierFor));

	return `${GENERATED_HEADER}\n${imports}\n\n${services}\n`;
}

// True when at least one service module exists. The plugin's source slots
// use this to skip emitting a header-only barrel (and the server's barrel
// import) for consumers without services.
export function hasServiceFiles(cwd: string): boolean {
	try {
		return readdirSync(servicesDir(cwd)).some(isServiceFile);
	} catch {
		return false;
	}
}
