import {
	dedupeImports,
	renderTsSourceFile,
	type TsExpression,
	type TsImportSpec,
	type TsSourceFile,
} from "@fcalell/cli/ast";
import type {
	CodegenEntryPayload,
	CodegenExpoConfigPayload,
	CodegenMetroPayload,
	ExpoConfigPlugin,
	MetroRequireSpec,
} from "../types";

const GENERATED_BANNER =
	"// Generated by @fcalell/plugin-expo — do not edit.\n" +
	"// Configure native behaviour through stack.config.ts, not this file.\n";

function ensureTrailingNewline(source: string): string {
	return source.endsWith("\n") ? source : `${source}\n`;
}

// Render a JSON-serializable value as a JS literal at the given indent. JSON's
// output is valid JS, so this is just `JSON.stringify` with the continuation
// lines re-indented to sit inside the surrounding literal.
function renderJsLiteral(value: unknown, indent: string): string {
	const json = JSON.stringify(value, null, "\t");
	return json.replace(/\n/g, `\n${indent}`);
}

// ── metro.config.js (CommonJS) ─────────────────────────────────────

const BASE_METRO_REQUIRE: MetroRequireSpec = {
	names: ["getDefaultConfig"],
	module: "expo/metro-config",
};

export function aggregateMetroConfig(payload: CodegenMetroPayload): string {
	const requires = dedupeMetroRequires([
		BASE_METRO_REQUIRE,
		...payload.requires,
	]);
	const wrappers = [...payload.wrappers].sort((a, b) => {
		const order = (a.order ?? 0) - (b.order ?? 0);
		return order !== 0 ? order : a.callee.localeCompare(b.callee);
	});

	const lines: string[] = [GENERATED_BANNER.trimEnd(), ""];

	for (const req of requires) {
		lines.push(
			`const { ${req.names.join(", ")} } = require(${JSON.stringify(req.module)});`,
		);
	}
	lines.push("");

	// `const` when nothing reassigns it; `let` + reassignment for each wrapper.
	const binding = wrappers.length > 0 ? "let" : "const";
	lines.push(`${binding} config = getDefaultConfig(__dirname);`);
	for (const wrapper of wrappers) {
		const args =
			wrapper.options === undefined
				? "config"
				: `config, ${renderJsLiteral(wrapper.options, "")}`;
		lines.push(`config = ${wrapper.callee}(${args});`);
	}
	lines.push("");
	lines.push("module.exports = config;");

	return ensureTrailingNewline(lines.join("\n"));
}

// Dedupe by module, merging the destructured names so two contributors asking
// for different exports of the same module collapse into one require line.
function dedupeMetroRequires(specs: MetroRequireSpec[]): MetroRequireSpec[] {
	const byModule = new Map<string, Set<string>>();
	const order: string[] = [];
	for (const spec of specs) {
		let names = byModule.get(spec.module);
		if (!names) {
			names = new Set();
			byModule.set(spec.module, names);
			order.push(spec.module);
		}
		for (const name of spec.names) names.add(name);
	}
	order.sort((a, b) => a.localeCompare(b));
	return order.map((module) => ({
		module,
		names: [...(byModule.get(module) ?? [])].sort((a, b) => a.localeCompare(b)),
	}));
}

// ── app.config.ts ──────────────────────────────────────────────────

function renderConfigPlugin(plugin: ExpoConfigPlugin): string {
	const value =
		plugin.options === undefined ? plugin.name : [plugin.name, plugin.options];
	return renderJsLiteral(value, "\t\t");
}

export function aggregateExpoConfig(payload: CodegenExpoConfigPayload): string {
	const props: string[] = [
		`\tname: ${JSON.stringify(payload.name)},`,
		`\tslug: ${JSON.stringify(payload.slug)},`,
		`\tscheme: ${JSON.stringify(payload.scheme)},`,
		`\tversion: "1.0.0",`,
		`\torientation: "portrait",`,
		// "automatic" lets the app honour the OS light/dark setting — required
		// for the design system's light + Notturno themes.
		`\tuserInterfaceStyle: "automatic",`,
		`\tnewArchEnabled: true,`,
		`\tios: {`,
		`\t\tsupportsTablet: false,`,
		`\t\tbundleIdentifier: ${JSON.stringify(payload.bundleIdentifier)},`,
		`\t},`,
		`\tandroid: {`,
		`\t\tpackage: ${JSON.stringify(payload.androidPackage)},`,
		`\t},`,
	];

	const pluginLines = payload.plugins.map(
		(p) => `\t\t${renderConfigPlugin(p)},`,
	);
	props.push(`\tplugins: [`, ...pluginLines, `\t],`);

	if (payload.typedRoutes) {
		props.push(`\texperiments: {`, `\t\ttypedRoutes: true,`, `\t},`);
	}

	const body = [
		GENERATED_BANNER.trimEnd(),
		"",
		'import type { ExpoConfig } from "expo/config";',
		"",
		"const config: ExpoConfig = {",
		...props,
		"};",
		"",
		"export default config;",
	].join("\n");

	return ensureTrailingNewline(body);
}

// ── entry.tsx ──────────────────────────────────────────────────────

function requireContextCall(appContextPath: string): TsExpression {
	return {
		kind: "call",
		callee: {
			kind: "member",
			object: { kind: "identifier", name: "require" },
			property: "context",
		},
		args: [{ kind: "string", value: appContextPath }],
	};
}

// Render `.stack/entry.tsx`. Composes contributed providers (outermost =
// lowest `order`, mirroring solid's provider nesting) around the expo-router
// root. Returns null when routing is disabled — there is no root to mount.
export function aggregateEntry(payload: CodegenEntryPayload): string | null {
	if (payload.appContextPath === null) return null;

	const root: TsExpression = {
		kind: "jsx",
		tag: "ExpoRoot",
		props: [
			{ name: "context", value: requireContextCall(payload.appContextPath) },
		],
		children: [],
		selfClosing: true,
	};

	// Providers arrive pre-sorted ascending by `order` from the owning list
	// slot. Wrap from the inside out so the first provider is the outermost.
	let inner = root;
	for (let i = payload.providers.length - 1; i >= 0; i--) {
		const spec = payload.providers[i];
		if (!spec) continue;
		const children: TsExpression[] =
			spec.siblings && spec.siblings.length > 0
				? [inner, ...spec.siblings]
				: [inner];
		inner = {
			kind: "jsx",
			tag: spec.wrap.identifier,
			props: (spec.wrap.props ?? []).map((p) => ({
				name: p.name,
				value: p.value,
			})),
			children,
		};
	}

	const imports: TsImportSpec[] = dedupeImports([
		{ source: "expo", named: ["registerRootComponent"] },
		{ source: "expo-router", named: ["ExpoRoot"] },
		...payload.imports,
		...payload.providers.flatMap((p) => p.imports),
	]);

	const spec: TsSourceFile = {
		imports,
		statements: [
			{
				kind: "const",
				name: "App",
				exported: true,
				value: { kind: "arrow", params: [], body: inner },
			},
			{
				kind: "expression",
				value: {
					kind: "call",
					callee: { kind: "identifier", name: "registerRootComponent" },
					args: [{ kind: "identifier", name: "App" }],
				},
			},
		],
	};

	return ensureTrailingNewline(renderTsSourceFile(spec));
}

// ── routes.d.ts ────────────────────────────────────────────────────
//
// Thin by design: expo-router runs its own typed-route generator (gated by
// `experiments.typedRoutes`) and writes the augmentation it references here.
// Re-emitting that generator would duplicate Expo's work and drift from it.
export function buildRoutesDts(): string {
	return ensureTrailingNewline(
		`${GENERATED_BANNER.trimEnd()}\n/// <reference types="expo-router/types" />`,
	);
}
