import { createRequire } from "node:module";
import { join } from "node:path";

// The app's typed routes: expo-router's own declaration, generated by the
// generator the app's Expo CLI runs (`@expo/router-server`, reached through
// the app's `expo` and `@expo/cli`), over the route files the app's
// expo-router would mount. It augments `ExpoRouter.__routes`, which
// expo-router's `Href` reads, so an `href` to a path no route file serves
// fails the type-check.

interface RequireContext {
	keys(): string[];
}

interface RouterServer {
	getTypedRoutesDeclarationFile(ctx: RequireContext): string;
}

interface ExpoRouterTesting {
	requireContext(
		base: string,
		scanSubDirectories: boolean,
		pattern: RegExp,
	): RequireContext;
}

interface ExpoRouterContext {
	EXPO_ROUTER_CTX_IGNORE: RegExp;
}

const BANNER = "// Generated by @fcalell/plugin-expo — do not edit.\n";

export function buildRoutesDts(root: string, appDir: string): string {
	let serverRequire: NodeRequire;
	try {
		const app = createRequire(join(root, "package.json"));
		const expo = createRequire(app.resolve("expo/package.json"));
		const cli = createRequire(expo.resolve("@expo/cli/package.json"));
		serverRequire = createRequire(
			cli.resolve("@expo/router-server/package.json"),
		);
	} catch (error) {
		throw new Error(
			"expo: typed routes are generated by the app's installed `expo`; run `pnpm install` first.",
			{ cause: error },
		);
	}
	// expo-router is the one the generator resolves, so the route files are
	// read by the rules that generator was built against.
	const server: RouterServer = serverRequire(
		"./build/typed-routes/generate.js",
	);
	const testing: ExpoRouterTesting = serverRequire(
		"expo-router/internal/testing",
	);
	const context: ExpoRouterContext = serverRequire("expo-router/_ctx-shared");
	const routes = testing.requireContext(
		join(root, appDir),
		true,
		context.EXPO_ROUTER_CTX_IGNORE,
	);
	return BANNER + server.getTypedRoutesDeclarationFile(routes);
}
