import type { ScaffoldSpec } from "../ast/index.ts";
import type {
	BuildStep,
	DeployCheck,
	DeployStep,
	DevReadyTask,
	GeneratedFile,
	GuideEntry,
	LintPlugin,
	ProcessSpec,
	PromptSpec,
	WatcherSpec,
} from "../specs.ts";
import { type Contribution, type Slot, slot } from "./slots.ts";

// CLI-owned slot tokens — every value the core `stack` CLI consumes from
// plugins flows through one of these. The lifecycle is fixed: each command
// resolves a known set of these slots and acts on the values.
//
// `source: "cli"` is the convention for tokens that aren't owned by a plugin.
// Phase-sorted list slots (buildSteps / deploySteps) carry phase+order on the
// spec itself — `sortBy` at the slot level handles ordering at resolution.
const SOURCE = "cli";

const phaseOrder = { pre: 0, main: 1, post: 2 } as const;

function comparePhaseOrder<T extends { phase: "pre" | "main" | "post" }>(
	a: T,
	b: T,
): number {
	return phaseOrder[a.phase] - phaseOrder[b.phase];
}

export const cliSlots = {
	initPrompts: slot.list<PromptSpec>({ source: SOURCE, name: "initPrompts" }),
	initScaffolds: slot.list<ScaffoldSpec>({
		source: SOURCE,
		name: "initScaffolds",
		// Two plugins claiming the same target is a programming error — surface
		// it at compose time rather than waiting for the writer to detect it.
		uniqueBy: (s) => s.target,
	}),
	initDeps: slot.map<string>({ source: SOURCE, name: "initDeps" }),
	initDevDeps: slot.map<string>({ source: SOURCE, name: "initDevDeps" }),
	// Arbitrary top-level package.json fields a plugin needs in the consumer
	// manifest (e.g. Expo's `main`). Applied write-if-absent at init/add so a
	// consumer-edited value is never clobbered. Duplicate keys across plugins
	// throw — two plugins fighting over `main` is a real conflict, not a merge.
	packageJsonFields: slot.map<unknown>({
		source: SOURCE,
		name: "packageJsonFields",
	}),
	gitignore: slot.list<string>({ source: SOURCE, name: "gitignore" }),
	artifactFiles: slot.list<GeneratedFile>({
		source: SOURCE,
		name: "artifactFiles",
	}),
	// The pages the CLI indexes into `.stack/guide.md`, auto-wired from
	// `plugin({ guide })` with the plugin's name as the domain and its package.
	// Sorted by domain so the index is independent of config order. A page two
	// plugins list (a shared package's) is indexed once.
	guide: slot.list<GuideEntry>({
		source: SOURCE,
		name: "guide",
		sortBy: (a, b) => a.domain.localeCompare(b.domain),
	}),
	// The Biome plugins the consumer's lint runs on its own sources, from the
	// package that owns the rules. Rendered into `.stack/biome.json`.
	lintPlugins: slot.list<LintPlugin>({
		source: SOURCE,
		name: "lintPlugins",
		uniqueBy: (p) => p.path,
	}),
	postWrite: slot.list<() => Promise<void>>({
		source: SOURCE,
		name: "postWrite",
	}),
	devProcesses: slot.list<ProcessSpec>({
		source: SOURCE,
		name: "devProcesses",
		// Process names appear in the supervisor's log prefix; two processes
		// sharing a name produce indistinguishable output and ambiguous
		// shutdown/restart targeting.
		uniqueBy: (p) => p.name,
	}),
	devWatchers: slot.list<WatcherSpec>({
		source: SOURCE,
		name: "devWatchers",
		uniqueBy: (w) => w.name,
	}),
	devReadySetup: slot.list<DevReadyTask>({
		source: SOURCE,
		name: "devReadySetup",
		uniqueBy: (t) => t.name,
	}),
	buildSteps: slot.list<BuildStep>({
		source: SOURCE,
		name: "buildSteps",
		sortBy: comparePhaseOrder,
		uniqueBy: (s) => s.name,
	}),
	deployChecks: slot.list<DeployCheck>({
		source: SOURCE,
		name: "deployChecks",
	}),
	deploySteps: slot.list<DeployStep>({
		source: SOURCE,
		name: "deploySteps",
		sortBy: comparePhaseOrder,
		uniqueBy: (s) => s.name,
	}),
	removeFiles: slot.list<string>({ source: SOURCE, name: "removeFiles" }),
	removeDeps: slot.list<string>({ source: SOURCE, name: "removeDeps" }),
	removeDevDeps: slot.list<string>({ source: SOURCE, name: "removeDevDeps" }),
	// Consumer tsconfig.json `compilerOptions.paths` entries a plugin's
	// generated code needs resolved (e.g. plugin-api's `virtual:stack-procedure`
	// alias). Consumed once, at `stack init` — tsconfig.json is scaffolded, not
	// regenerated by `stack generate`.
	tsconfigPaths: slot.map<string[]>({ source: SOURCE, name: "tsconfigPaths" }),
	// Consumer tsconfig.json `compilerOptions.types` entries a plugin's runtime
	// needs globally in scope (e.g. plugin-native-ui's uniwind className
	// augmentation). Same consumption point as `tsconfigPaths`.
	tsconfigTypes: slot.list<string>({ source: SOURCE, name: "tsconfigTypes" }),
	// The consumer tsconfig, relative to its root, that a bundler compiling
	// the worker reads (its `paths` carry `tsconfigPaths`): the worker project
	// when `stack init` splits the config, else the single root one. The CLI
	// contributes it from the same layout the tsconfig template writes.
	workerTsconfig: slot.value<string>({
		source: SOURCE,
		name: "workerTsconfig",
		seed: () => "tsconfig.json",
	}),
} as const;

export type CliSlots = typeof cliSlots;

// Shorthand for the canonical "resolve a *Source slot, write it as an
// artifact, skip on null" pattern. A null source means the upstream
// derivation chose not to emit anything (e.g. no runtimes registered) — the
// contribution returns undefined and the artifactFiles list drops it.
export function emitArtifact(
	path: string,
	source: Slot<string | null>,
): Contribution<GeneratedFile[]> {
	return cliSlots.artifactFiles.contribute(async (ctx) => {
		const content = await ctx.resolve(source);
		if (content === null) return undefined;
		return { path, content };
	});
}
