import { existsSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";
import { log } from "@clack/prompts";
import { builders, generateCode, parseModule } from "magicast";
import { parse as parseToml, stringify as stringifyToml } from "smol-toml";
import type { BindingDeclaration } from "#config";
import type {
	CodegenWorkerPayload,
	ViteImportSpec,
	VitePluginCallSpec,
	WorkerUseSpec,
} from "#events";

const GENERATED_HEADER = "// Generated by @fcalell/cli — do not edit.";

// Values that mean "the generated entry" — written either relative to the
// consumer's repo root (".stack/worker.ts") or relative to the emitted
// .stack/wrangler.toml ("worker.ts"). Either is treated as intent to use
// the generated worker and will not trigger a custom-main warning.
const GENERATED_MAIN_VALUES = new Set([
	"worker.ts",
	"./worker.ts",
	".stack/worker.ts",
	"./.stack/worker.ts",
]);

// ── Binding type map ─────────────────────────────────────────────

const BINDING_TYPE_MAP: Record<BindingDeclaration["type"], string> = {
	d1: "D1Database",
	r2: "R2Bucket",
	kv: "KVNamespace",
	queue: "Queue",
	rate_limiter: "RateLimiter",
	durable_object: "DurableObjectNamespace",
	service: "Fetcher",
	var: "string",
	secret: "string",
};

// ── generateEnvDts ───────────────────────────────────────────────

export function generateEnvDts(bindings: BindingDeclaration[]): string {
	const lines: string[] = [GENERATED_HEADER, ""];

	if (bindings.length === 0) {
		lines.push("interface Env {}");
	} else {
		lines.push("interface Env {");
		for (const b of bindings) {
			const tsType = BINDING_TYPE_MAP[b.type] ?? "unknown";
			lines.push(`\t${b.name}: ${tsType};`);
		}
		lines.push("}");
	}

	lines.push("");
	return lines.join("\n");
}

// ── generateWranglerToml ─────────────────────────────────────────

// Shape of the TOML object we build before stringifying. All fields are
// optional because consumers' wrangler.toml may or may not set them; the
// generator fills in what's missing and appends our bindings.
interface WranglerTable {
	name?: string;
	compatibility_date?: string;
	main?: string;
	d1_databases?: Array<{
		binding: string;
		database_id: string;
		database_name?: string;
	}>;
	kv_namespaces?: Array<{ binding: string; id: string }>;
	r2_buckets?: Array<{ binding: string; bucket_name: string }>;
	unsafe?: {
		bindings?: Array<{
			name: string;
			type: "ratelimit";
			limit?: number;
			period?: number;
		}>;
	};
	vars?: Record<string, string>;
	[key: string]: unknown;
}

function appendBindings(
	table: WranglerTable,
	bindings: BindingDeclaration[],
): void {
	const d1 = bindings.filter((b) => b.type === "d1");
	if (d1.length > 0) {
		table.d1_databases ??= [];
		for (const b of d1) {
			const entry: {
				binding: string;
				database_id: string;
				database_name?: string;
			} = {
				binding: b.name,
				database_id: b.databaseId ?? "",
			};
			if (b.databaseName) entry.database_name = b.databaseName;
			table.d1_databases.push(entry);
		}
	}

	const kv = bindings.filter((b) => b.type === "kv");
	if (kv.length > 0) {
		table.kv_namespaces ??= [];
		for (const b of kv) {
			table.kv_namespaces.push({
				binding: b.name,
				id: b.kvNamespaceId ?? "",
			});
		}
	}

	const r2 = bindings.filter((b) => b.type === "r2");
	if (r2.length > 0) {
		table.r2_buckets ??= [];
		for (const b of r2) {
			table.r2_buckets.push({
				binding: b.name,
				bucket_name: b.bucketName ?? "",
			});
		}
	}

	const rateLimiters = bindings.filter((b) => b.type === "rate_limiter");
	if (rateLimiters.length > 0) {
		table.unsafe ??= {};
		table.unsafe.bindings ??= [];
		for (const b of rateLimiters) {
			const entry: {
				name: string;
				type: "ratelimit";
				limit?: number;
				period?: number;
			} = { name: b.name, type: "ratelimit" };
			if (b.rateLimit) {
				entry.limit = b.rateLimit.limit;
				entry.period = b.rateLimit.period;
			}
			table.unsafe.bindings.push(entry);
		}
	}

	const varsAndSecrets = bindings.filter(
		(b) => b.type === "var" || b.type === "secret",
	);
	if (varsAndSecrets.length > 0) {
		table.vars ??= {};
		for (const b of varsAndSecrets) {
			table.vars[b.name] = b.devDefault ?? "";
		}
	}
}

export function generateWranglerToml(opts: {
	consumerWrangler: string | null;
	bindings: BindingDeclaration[];
	name?: string;
}): string {
	let table: WranglerTable;

	if (opts.consumerWrangler) {
		try {
			table = parseToml(opts.consumerWrangler) as WranglerTable;
		} catch (err) {
			const msg = err instanceof Error ? err.message : String(err);
			throw new Error(`Failed to parse consumer wrangler.toml: ${msg}`);
		}
		if (table.main === undefined) {
			table.main = "worker.ts";
		} else if (
			typeof table.main === "string" &&
			!GENERATED_MAIN_VALUES.has(table.main)
		) {
			log.warn(
				`Custom \`main\` detected in wrangler.toml (${table.main}); stack will not override it. Ensure it re-exports from .stack/worker.ts, or remove the line to let stack manage it.`,
			);
		}
	} else {
		const date = new Date().toISOString().split("T")[0] ?? "";
		table = {
			name: opts.name ?? "stack-app",
			compatibility_date: date,
			main: "worker.ts",
		};
	}

	appendBindings(table, opts.bindings);

	const out = stringifyToml(table as Record<string, unknown>);
	return out.endsWith("\n") ? out : `${out}\n`;
}

// ── generateDevVars ──────────────────────────────────────────────

export function generateDevVars(bindings: BindingDeclaration[]): string | null {
	const secrets = bindings.filter((b) => b.type === "secret");
	if (secrets.length === 0) return null;

	const lines = secrets.map((b) => `${b.name}=${b.devDefault ?? "changeme"}`);
	return `${lines.join("\n")}\n`;
}

// ── Virtual worker ──────────────────────────────────────────────

export function hasRuntimeExport(packageName: string): boolean {
	const pkg = readPackageJson(packageName);
	return !!pkg?.exports?.["./runtime"];
}

function readPackageJson(
	packageName: string,
): { exports?: Record<string, unknown> } | null {
	// Walk from the package's resolved main up to its package.json. Going
	// through `require.resolve(pkg/package.json)` would fail for packages
	// whose exports map doesn't expose `./package.json`.
	// Resolve twice: first from this module, then from the consumer's cwd
	// — the CLI's own `node_modules` may not contain the plugin when run
	// via a symlinked bin.
	for (const reqFn of [
		requireFromSelf,
		() => createRequire(join(process.cwd(), "package.json")),
	]) {
		try {
			const req = reqFn();
			const mainPath = req.resolve(packageName);
			return readJsonWalkingUp(mainPath);
		} catch {}
	}
	return null;
}

function requireFromSelf(): NodeJS.Require {
	return createRequire(import.meta.url);
}

function readJsonWalkingUp(
	startPath: string,
): { exports?: Record<string, unknown> } | null {
	let dir = join(startPath, "..");
	for (let i = 0; i < 10; i++) {
		const candidate = join(dir, "package.json");
		if (existsSync(candidate)) {
			return JSON.parse(readFileSync(candidate, "utf-8"));
		}
		const parent = join(dir, "..");
		if (parent === dir) return null;
		dir = parent;
	}
	return null;
}

export function serializeOptions(options: Record<string, unknown>): string {
	return JSON.stringify(options, null, "\t");
}

// Renders the argument list for a factory call. JSON-serializable data fields
// stay double-quoted; identifier fields remain bare. Using shorthand
// (`{ schema }`) when key === identifier name.
function renderFactoryArgument(
	options: Record<string, unknown> | undefined,
	identifierFields: Record<string, string> | undefined,
): string {
	const optionEntries = options ? Object.entries(options) : [];
	const idEntries = identifierFields ? Object.entries(identifierFields) : [];

	if (optionEntries.length === 0 && idEntries.length === 0) return "";

	if (optionEntries.length === 0) {
		const parts = idEntries.map(([k, id]) => (k === id ? id : `${k}: ${id}`));
		return `{ ${parts.join(", ")} }`;
	}

	const body: string[] = ["{"];
	for (const [k, v] of optionEntries) {
		const value = JSON.stringify(v, null, "\t").replace(/\n/g, "\n\t");
		body.push(`\t${JSON.stringify(k)}: ${value},`);
	}
	for (const [k, id] of idEntries) {
		body.push(k === id ? `\t${id},` : `\t${k}: ${id},`);
	}
	body.push("}");
	return body.join("\n");
}

function renderUse(spec: WorkerUseSpec): string {
	if (spec.kind === "identifier") {
		return `\t.use(${spec.identifier})`;
	}
	const arg = renderFactoryArgument(spec.options, spec.identifierFields);
	return `\t.use(${spec.factoryName}(${arg}))`;
}

// ── generateViteConfig ──────────────────────────────────────────

// Base imports and plugin calls that ship with every .stack/vite.config.ts.
// Plugins layer additional imports/plugins on top via the Configure payload.
const VITE_CONFIG_SKELETON = `import { defineConfig } from "vite";
import tailwindcss from "@tailwindcss/vite";
import { themeFontsPlugin } from "@fcalell/plugin-vite/preset";

export default defineConfig({
\tplugins: [tailwindcss(), themeFontsPlugin()],
});
`;

// AST-based builder. Plugins push structured ImportSpec / PluginCallSpec
// values; magicast composes the final module so identifiers, option objects,
// and import shapes are all round-tripped correctly.
export function generateViteConfig(payload: {
	viteImports: ViteImportSpec[];
	vitePluginCalls: VitePluginCallSpec[];
}): string {
	const mod = parseModule(VITE_CONFIG_SKELETON);

	for (const imp of payload.viteImports) {
		if (imp.default) {
			mod.imports.$append({
				from: imp.from,
				imported: "default",
				local: imp.default,
			});
		}
		for (const named of imp.named ?? []) {
			mod.imports.$append({ from: imp.from, imported: named });
		}
	}

	// biome-ignore lint/suspicious/noExplicitAny: magicast proxies are dynamically typed
	const config = (mod.exports.default as any).$args[0];
	for (const call of payload.vitePluginCalls) {
		const args = call.options ? [call.options] : [];
		config.plugins.push(builders.functionCall(call.name, ...args));
	}

	const { code } = generateCode(mod, {
		format: false,
		useTabs: true,
		tabWidth: 4,
		quote: "double",
	});
	return code.endsWith("\n") ? code : `${code}\n`;
}

// ── generateVirtualWorker ───────────────────────────────────────

// Pure assembler — no plugin-name awareness. Every runtime-capable plugin
// contributes its imports and a use-spec via the Codegen.Worker event;
// exactly one plugin claims the `root` role.
export function generateVirtualWorker(payload: CodegenWorkerPayload): string {
	const lines: string[] = [GENERATED_HEADER, "", ...payload.imports, ""];

	if (payload.root) {
		const rootArg = renderFactoryArgument(
			payload.root.options,
			payload.root.identifierFields,
		);
		lines.push(`const worker = ${payload.root.factoryName}(${rootArg})`);
		for (const use of payload.uses) {
			lines.push(renderUse(use));
		}
		lines.push(`\t.handler(${payload.handlerArg});`);
		lines.push("");
		for (const line of payload.tailLines) {
			lines.push(line);
		}
	}

	lines.push("");
	return lines.join("\n");
}
