import { createRequire } from "node:module";
import { join } from "node:path";
import { log } from "@clack/prompts";
import type { BindingDeclaration } from "#config";

const GENERATED_HEADER = "// Generated by @fcalell/cli — do not edit.";

// Values that mean "the generated entry" — written either relative to the
// consumer's repo root (".stack/worker.ts") or relative to the emitted
// .stack/wrangler.toml ("worker.ts"). Either is treated as intent to use
// the generated worker and will not trigger a custom-main warning.
const GENERATED_MAIN_VALUES = new Set([
	"worker.ts",
	"./worker.ts",
	".stack/worker.ts",
	"./.stack/worker.ts",
]);

const MAIN_LINE_RE = /^main\s*=\s*["']([^"']*)["']\s*$/m;

// ── Binding type map ─────────────────────────────────────────────

const BINDING_TYPE_MAP: Record<BindingDeclaration["type"], string> = {
	d1: "D1Database",
	r2: "R2Bucket",
	kv: "KVNamespace",
	queue: "Queue",
	rate_limiter: "RateLimiter",
	durable_object: "DurableObjectNamespace",
	service: "Fetcher",
	var: "string",
	secret: "string",
};

// ── generateEnvDts ───────────────────────────────────────────────

export function generateEnvDts(bindings: BindingDeclaration[]): string {
	const lines: string[] = [GENERATED_HEADER, ""];

	if (bindings.length === 0) {
		lines.push("interface Env {}");
	} else {
		lines.push("interface Env {");
		for (const b of bindings) {
			const tsType = BINDING_TYPE_MAP[b.type] ?? "unknown";
			lines.push(`\t${b.name}: ${tsType};`);
		}
		lines.push("}");
	}

	lines.push("");
	return lines.join("\n");
}

// ── generateWranglerToml ─────────────────────────────────────────

export function generateWranglerToml(opts: {
	consumerWrangler: string | null;
	bindings: BindingDeclaration[];
	name?: string;
}): string {
	const sections: string[] = [];

	if (opts.consumerWrangler) {
		const match = opts.consumerWrangler.match(MAIN_LINE_RE);
		if (!match) {
			// No main line found — insert one pointing at the generated entry.
			const consumerLines = opts.consumerWrangler.split("\n");
			const insertIdx = consumerLines.findIndex(
				(l) => l.trim() !== "" && !l.trim().startsWith("#"),
			);
			if (insertIdx >= 0) {
				consumerLines.splice(insertIdx + 1, 0, 'main = "worker.ts"');
			} else {
				consumerLines.push('main = "worker.ts"');
			}
			sections.push(consumerLines.join("\n"));
		} else {
			const currentMain = match[1] ?? "";
			if (!GENERATED_MAIN_VALUES.has(currentMain)) {
				// Consumer set a custom `main` — preserve it, but warn so they know
				// stack is no longer pointing wrangler at its generated entry.
				log.warn(
					`Custom \`main\` detected in wrangler.toml (${currentMain}); stack will not override it. Ensure it re-exports from .stack/worker.ts, or remove the line to let stack manage it.`,
				);
			}
			// Leave the consumer's main line untouched whether it already points
			// at the generated entry or at a custom override.
			sections.push(opts.consumerWrangler);
		}
	} else {
		const name = opts.name ?? "stack-app";
		const date = new Date().toISOString().split("T")[0];
		sections.push(
			`name = "${name}"\ncompatibility_date = "${date}"\nmain = "worker.ts"`,
		);
	}

	const d1 = opts.bindings.filter((b) => b.type === "d1");
	for (const b of d1) {
		const lines = [
			"",
			"[[d1_databases]]",
			`binding = "${b.name}"`,
			`database_id = "${b.databaseId ?? ""}"`,
		];
		if (b.databaseName) lines.push(`database_name = "${b.databaseName}"`);
		sections.push(lines.join("\n"));
	}

	const kv = opts.bindings.filter((b) => b.type === "kv");
	for (const b of kv) {
		const lines = [
			"",
			"[[kv_namespaces]]",
			`binding = "${b.name}"`,
			`id = "${b.kvNamespaceId ?? ""}"`,
		];
		sections.push(lines.join("\n"));
	}

	const r2 = opts.bindings.filter((b) => b.type === "r2");
	for (const b of r2) {
		const lines = [
			"",
			"[[r2_buckets]]",
			`binding = "${b.name}"`,
			`bucket_name = "${b.bucketName ?? ""}"`,
		];
		sections.push(lines.join("\n"));
	}

	const rateLimiters = opts.bindings.filter((b) => b.type === "rate_limiter");
	for (const b of rateLimiters) {
		const lines = [
			"",
			"[[unsafe.bindings]]",
			`name = "${b.name}"`,
			'type = "ratelimit"',
		];
		if (b.rateLimit) {
			lines.push(`limit = ${b.rateLimit.limit}`);
			lines.push(`period = ${b.rateLimit.period}`);
		}
		sections.push(lines.join("\n"));
	}

	const varsAndSecrets = opts.bindings.filter(
		(b) => b.type === "var" || b.type === "secret",
	);
	if (varsAndSecrets.length > 0) {
		const lines = ["", "[vars]"];
		for (const b of varsAndSecrets) {
			lines.push(`${b.name} = "${b.devDefault ?? ""}"`);
		}
		sections.push(lines.join("\n"));
	}

	return `${sections.join("\n")}\n`;
}

// ── generateDevVars ──────────────────────────────────────────────

export function generateDevVars(bindings: BindingDeclaration[]): string | null {
	const secrets = bindings.filter((b) => b.type === "secret");
	if (secrets.length === 0) return null;

	const lines = secrets.map((b) => `${b.name}=${b.devDefault ?? "changeme"}`);
	return `${lines.join("\n")}\n`;
}

// ── Virtual worker ──────────────────────────────────────────────

import { existsSync, readFileSync } from "node:fs";
import type { CodegenWorkerPayload } from "#events";

export function hasRuntimeExport(packageName: string): boolean {
	const pkg = readPackageJson(packageName);
	return !!pkg?.exports?.["./runtime"];
}

function readPackageJson(
	packageName: string,
): { exports?: Record<string, unknown> } | null {
	// Walk from the package's resolved main up to its package.json. Going
	// through `require.resolve(pkg/package.json)` would fail for packages
	// whose exports map doesn't expose `./package.json`.
	// Resolve twice: first from this module, then from the consumer's cwd
	// — the CLI's own `node_modules` may not contain the plugin when run
	// via a symlinked bin.
	for (const reqFn of [
		requireFromSelf,
		() => createRequire(join(process.cwd(), "package.json")),
	]) {
		try {
			const req = reqFn();
			const mainPath = req.resolve(packageName);
			return readJsonWalkingUp(mainPath);
		} catch {}
	}
	return null;
}

function requireFromSelf(): NodeJS.Require {
	return createRequire(import.meta.url);
}

function readJsonWalkingUp(
	startPath: string,
): { exports?: Record<string, unknown> } | null {
	let dir = join(startPath, "..");
	for (let i = 0; i < 10; i++) {
		const candidate = join(dir, "package.json");
		if (existsSync(candidate)) {
			return JSON.parse(readFileSync(candidate, "utf-8"));
		}
		const parent = join(dir, "..");
		if (parent === dir) return null;
		dir = parent;
	}
	return null;
}

export function serializeOptions(options: Record<string, unknown>): string {
	return JSON.stringify(options, null, "\t");
}

// Pure assembler — no plugin-name awareness. Every runtime-capable plugin
// contributes its imports and a `.use(...)` line via the Codegen.Worker
// event; exactly one plugin claims the `root` role.
export function generateVirtualWorker(payload: CodegenWorkerPayload): string {
	const lines: string[] = [GENERATED_HEADER, "", ...payload.imports, ""];

	if (payload.root) {
		lines.push(
			`const worker = ${payload.root.factoryName}(${payload.root.optionsLiteral})`,
		);
		for (const line of payload.useLines) {
			lines.push(line);
		}
		lines.push(`\t.handler(${payload.handlerArg});`);
		lines.push("");
		for (const line of payload.tailLines) {
			lines.push(line);
		}
	}

	lines.push("");
	return lines.join("\n");
}
