import { log } from "@clack/prompts";
import { beforeEach, describe, expect, it, vi } from "vitest";
import {
	generateVirtualWorker,
	generateWranglerToml,
	serializeOptions,
} from "#lib/codegen";

vi.mock("@clack/prompts", () => ({
	log: {
		info: vi.fn(),
		warn: vi.fn(),
		success: vi.fn(),
		error: vi.fn(),
	},
}));

describe("serializeOptions", () => {
	it("serializes plain objects as JSON", () => {
		const result = serializeOptions({ binding: "DB_MAIN" });
		expect(result).toContain('"binding"');
		expect(result).toContain('"DB_MAIN"');
	});

	it("handles empty objects", () => {
		expect(serializeOptions({})).toBe("{}");
	});
});

describe("generateVirtualWorker", () => {
	it("assembles imports, root factory, use chain, and tail lines", () => {
		const result = generateVirtualWorker({
			imports: [
				'import createWorker from "@fcalell/plugin-api/runtime";',
				'import dbRuntime from "@fcalell/plugin-db/runtime";',
				'import * as routes from "../src/worker/routes";',
			],
			root: {
				factoryName: "createWorker",
				options: { domain: "example.com" },
			},
			uses: [
				{
					kind: "factory",
					factoryName: "dbRuntime",
					options: { binding: "DB_MAIN" },
				},
			],
			handlerArg: "routes",
			tailLines: [
				"export type AppRouter = typeof worker._router;",
				"export default worker;",
			],
		});

		expect(result).toContain(
			'import createWorker from "@fcalell/plugin-api/runtime"',
		);
		expect(result).toContain(
			'import dbRuntime from "@fcalell/plugin-db/runtime"',
		);
		expect(result).toContain('import * as routes from "../src/worker/routes"');
		expect(result).toContain("const worker = createWorker(");
		expect(result).toContain('"domain": "example.com"');
		expect(result).toContain(".use(dbRuntime(");
		expect(result).toContain('"binding": "DB_MAIN"');
		expect(result).toContain(".handler(routes)");
		expect(result).toContain("export type AppRouter");
		expect(result).toContain("export default worker");
	});

	it("emits nothing for the worker body when no plugin claims root", () => {
		const result = generateVirtualWorker({
			imports: ['import dbRuntime from "@fcalell/plugin-db/runtime";'],
			root: null,
			uses: [],
			handlerArg: "",
			tailLines: [],
		});

		expect(result).not.toContain("createWorker");
		expect(result).not.toContain("const worker");
	});

	it("supports empty handlerArg for handler() without routes", () => {
		const result = generateVirtualWorker({
			imports: ['import createWorker from "@fcalell/plugin-api/runtime";'],
			root: { factoryName: "createWorker" },
			uses: [],
			handlerArg: "",
			tailLines: ["export default worker;"],
		});

		expect(result).toContain(".handler()");
	});

	it("renders identifier-only use-specs as bare identifiers", () => {
		const result = generateVirtualWorker({
			imports: [],
			root: { factoryName: "createWorker" },
			uses: [{ kind: "identifier", identifier: "middleware" }],
			handlerArg: "",
			tailLines: [],
		});

		expect(result).toContain(".use(middleware)");
	});

	it("renders identifier fields unquoted alongside JSON options", () => {
		const result = generateVirtualWorker({
			imports: [],
			root: { factoryName: "createWorker" },
			uses: [
				{
					kind: "factory",
					factoryName: "dbRuntime",
					options: { binding: "DB_MAIN" },
					identifierFields: { schema: "schema" },
				},
			],
			handlerArg: "",
			tailLines: [],
		});

		expect(result).toContain('"binding": "DB_MAIN"');
		expect(result).toContain("schema,");
		expect(result).not.toContain('"schema"');
	});

	it("writes the generated-by header first", () => {
		const result = generateVirtualWorker({
			imports: [],
			root: null,
			uses: [],
			handlerArg: "",
			tailLines: [],
		});

		const lines = result.split("\n");
		expect(lines[0]).toContain("Generated by @fcalell/cli");
	});
});

describe("generateWranglerToml", () => {
	beforeEach(() => {
		vi.mocked(log.warn).mockClear();
	});

	it("sets main to worker.ts in generated config", () => {
		const result = generateWranglerToml({
			consumerWrangler: null,
			bindings: [],
		});

		expect(result).toContain('main = "worker.ts"');
	});

	it("inserts main line when consumer wrangler.toml has none", () => {
		const consumer = 'name = "my-app"\ncompatibility_date = "2024-01-01"';
		const result = generateWranglerToml({
			consumerWrangler: consumer,
			bindings: [],
		});

		expect(result).toContain('main = "worker.ts"');
		expect(result).toContain('name = "my-app"');
		expect(log.warn).not.toHaveBeenCalled();
	});

	it("inserts main line when consumer wrangler.toml is effectively empty", () => {
		// File exists on disk but has no meaningful content (e.g. just comments
		// or whitespace). A non-empty string with no `main` falls through the
		// same "insert" path used above.
		const consumer = "# some comment\n";
		const result = generateWranglerToml({
			consumerWrangler: consumer,
			bindings: [],
		});

		expect(result).toContain('main = "worker.ts"');
		expect(log.warn).not.toHaveBeenCalled();
	});

	it("leaves main untouched and does not warn when it points at the generated entry", () => {
		const consumer = 'name = "my-app"\nmain = ".stack/worker.ts"';
		const result = generateWranglerToml({
			consumerWrangler: consumer,
			bindings: [],
		});

		expect(result).toContain('main = ".stack/worker.ts"');
		expect(log.warn).not.toHaveBeenCalled();
	});

	it("leaves a custom main untouched and warns the consumer", () => {
		const consumer =
			'name = "my-app"\nmain = "src/other.ts"\ncompatibility_date = "2024-01-01"';
		const result = generateWranglerToml({
			consumerWrangler: consumer,
			bindings: [],
		});

		expect(result).toContain('main = "src/other.ts"');
		expect(result).not.toContain('main = "worker.ts"');
		expect(log.warn).toHaveBeenCalledTimes(1);
		const message = vi.mocked(log.warn).mock.calls[0]?.[0] ?? "";
		expect(message).toContain("src/other.ts");
		expect(message).toContain("wrangler.toml");
	});
});
