import type { BindingDeclaration } from "@fcalell/config";
import type { CliPlugin } from "@fcalell/config/plugin";
import { describe, expect, it } from "vitest";
import {
	collectBindings,
	generateDevVars,
	generateEnvDts,
	generateVirtualWorker,
	generateWranglerToml,
} from "./codegen";

describe("generateEnvDts", () => {
	it("generates empty interface when no bindings", () => {
		const result = generateEnvDts([]);
		expect(result).toContain("interface Env {}");
	});

	it("maps d1 binding to D1Database", () => {
		const bindings: BindingDeclaration[] = [
			{ name: "DB_MAIN", type: "d1" },
		];
		const result = generateEnvDts(bindings);
		expect(result).toContain("DB_MAIN: D1Database;");
	});

	it("maps secret binding to string", () => {
		const bindings: BindingDeclaration[] = [
			{ name: "AUTH_SECRET", type: "secret" },
		];
		const result = generateEnvDts(bindings);
		expect(result).toContain("AUTH_SECRET: string;");
	});

	it("maps r2 binding to R2Bucket", () => {
		const bindings: BindingDeclaration[] = [
			{ name: "STORAGE", type: "r2" },
		];
		const result = generateEnvDts(bindings);
		expect(result).toContain("STORAGE: R2Bucket;");
	});

	it("maps kv binding to KVNamespace", () => {
		const bindings: BindingDeclaration[] = [
			{ name: "CACHE", type: "kv" },
		];
		const result = generateEnvDts(bindings);
		expect(result).toContain("CACHE: KVNamespace;");
	});

	it("maps rate_limiter binding to RateLimiter", () => {
		const bindings: BindingDeclaration[] = [
			{ name: "IP_LIMITER", type: "rate_limiter" },
		];
		const result = generateEnvDts(bindings);
		expect(result).toContain("IP_LIMITER: RateLimiter;");
	});

	it("maps multiple bindings", () => {
		const bindings: BindingDeclaration[] = [
			{ name: "DB_MAIN", type: "d1" },
			{ name: "AUTH_SECRET", type: "secret" },
			{ name: "APP_URL", type: "var" },
		];
		const result = generateEnvDts(bindings);
		expect(result).toContain("DB_MAIN: D1Database;");
		expect(result).toContain("AUTH_SECRET: string;");
		expect(result).toContain("APP_URL: string;");
	});

	it("includes generated header", () => {
		const result = generateEnvDts([]);
		expect(result).toContain("Generated by @fcalell/cli");
	});
});

describe("generateVirtualWorker", () => {
	it("generates worker with runtime plugins", () => {
		const result = generateVirtualWorker({
			plugins: [
				{
					name: "db",
					worker: {
						runtime: {
							importFrom: "@fcalell/plugin-db/runtime",
							factory: "dbRuntime",
						},
					},
				},
			],
			hasMiddleware: false,
			hasRoutes: true,
			callbackFiles: [],
		});
		expect(result).toContain("import config from");
		expect(result).toContain("dbRuntime");
		expect(result).toContain("import * as routes from");
		expect(result).toContain("export type AppRouter");
	});

	it("includes middleware import when present", () => {
		const result = generateVirtualWorker({
			plugins: [
				{
					name: "api",
					worker: {
						runtime: {
							importFrom: "@fcalell/plugin-api/runtime",
							factory: "apiRuntime",
						},
					},
				},
			],
			hasMiddleware: true,
			hasRoutes: false,
			callbackFiles: [],
		});
		expect(result).toContain("import middleware from");
		expect(result).toContain(".use(middleware)");
	});

	it("includes callback import when file exists", () => {
		const result = generateVirtualWorker({
			plugins: [
				{
					name: "auth",
					worker: {
						runtime: {
							importFrom: "@fcalell/plugin-auth/runtime",
							factory: "authRuntime",
						},
						callbacks: {
							required: true,
							defineHelper: "defineAuthCallbacks",
							importFrom: "@fcalell/plugin-auth",
						},
					},
				},
			],
			hasMiddleware: false,
			hasRoutes: false,
			callbackFiles: ["auth"],
		});
		expect(result).toContain("authCallbacks");
		expect(result).toContain("src/worker/plugins/auth");
	});

	it("does not include callback import when file missing", () => {
		const result = generateVirtualWorker({
			plugins: [
				{
					name: "auth",
					worker: {
						runtime: {
							importFrom: "@fcalell/plugin-auth/runtime",
							factory: "authRuntime",
						},
						callbacks: {
							required: true,
							defineHelper: "defineAuthCallbacks",
							importFrom: "@fcalell/plugin-auth",
						},
					},
				},
			],
			hasMiddleware: false,
			hasRoutes: false,
			callbackFiles: [],
		});
		expect(result).not.toContain("authCallbacks");
	});
});

describe("generateWranglerToml", () => {
	it("generates base config when no consumer wrangler", () => {
		const result = generateWranglerToml({
			consumerWrangler: null,
			bindings: [],
			name: "test-app",
		});
		expect(result).toContain('name = "test-app"');
		expect(result).toContain("compatibility_date");
		expect(result).toContain('main = ".stack/worker.ts"');
	});

	it("uses consumer wrangler when provided", () => {
		const result = generateWranglerToml({
			consumerWrangler: 'name = "my-app"\nmain = "custom.ts"',
			bindings: [],
		});
		expect(result).toContain('name = "my-app"');
		expect(result).toContain('main = "custom.ts"');
	});

	it("includes d1 database binding", () => {
		const result = generateWranglerToml({
			consumerWrangler: null,
			bindings: [
				{
					name: "DB_MAIN",
					type: "d1",
					databaseId: "abc-123",
					databaseName: "my-db",
				},
			],
		});
		expect(result).toContain("[[d1_databases]]");
		expect(result).toContain('binding = "DB_MAIN"');
		expect(result).toContain('database_id = "abc-123"');
		expect(result).toContain('database_name = "my-db"');
	});

	it("includes rate limiter binding", () => {
		const result = generateWranglerToml({
			consumerWrangler: null,
			bindings: [
				{
					name: "IP_LIMITER",
					type: "rate_limiter",
					rateLimit: { limit: 100, period: 60 },
				},
			],
		});
		expect(result).toContain("[[unsafe.bindings]]");
		expect(result).toContain('name = "IP_LIMITER"');
		expect(result).toContain('type = "ratelimit"');
	});
});

describe("generateDevVars", () => {
	it("returns empty string when no secrets", () => {
		const result = generateDevVars([]);
		expect(result).toBe("");
	});

	it("generates .dev.vars for secret bindings", () => {
		const bindings: BindingDeclaration[] = [
			{ name: "AUTH_SECRET", type: "secret" },
			{ name: "API_KEY", type: "secret", devDefault: "dev-key-123" },
		];
		const result = generateDevVars(bindings);
		expect(result).toContain("AUTH_SECRET=");
		expect(result).toContain("API_KEY=dev-key-123");
	});

	it("ignores non-secret bindings", () => {
		const bindings: BindingDeclaration[] = [
			{ name: "DB_MAIN", type: "d1" },
		];
		const result = generateDevVars(bindings);
		expect(result).toBe("");
	});
});

describe("collectBindings", () => {
	const makePlugin = (
		name: string,
		bindings: BindingDeclaration[],
	): { name: string; cli: CliPlugin; options: unknown } => ({
		name,
		cli: {
			name,
			label: name,
			detect: async () => false,
			scaffold: async () => {},
			bindings: () => bindings,
			generate: async () => [],
		},
		options: {},
	});

	it("collects bindings from all plugins", () => {
		const plugins = [
			makePlugin("db", [{ name: "DB_MAIN", type: "d1" }]),
			makePlugin("auth", [{ name: "AUTH_SECRET", type: "secret" }]),
		];
		const { bindings, collisions } = collectBindings(plugins);
		expect(bindings).toHaveLength(2);
		expect(collisions).toHaveLength(0);
	});

	it("detects collisions", () => {
		const plugins = [
			makePlugin("db", [{ name: "DB_MAIN", type: "d1" }]),
			makePlugin("other", [{ name: "DB_MAIN", type: "d1" }]),
		];
		const { collisions } = collectBindings(plugins);
		expect(collisions).toHaveLength(1);
		expect(collisions[0]?.name).toBe("DB_MAIN");
		expect(collisions[0]?.plugins).toEqual(["db", "other"]);
	});

	it("returns empty for no plugins", () => {
		const { bindings, collisions } = collectBindings([]);
		expect(bindings).toHaveLength(0);
		expect(collisions).toHaveLength(0);
	});
});
