import type { BindingDeclaration } from "@fcalell/config";
import type { CliPlugin, WorkerContribution } from "@fcalell/config/plugin";

const GENERATED_HEADER = "// Generated by @fcalell/cli — do not edit.";

const BINDING_TYPE_MAP: Record<BindingDeclaration["type"], string> = {
	d1: "D1Database",
	r2: "R2Bucket",
	kv: "KVNamespace",
	queue: "Queue",
	rate_limiter: "RateLimiter",
	durable_object: "DurableObjectNamespace",
	service: "Fetcher",
	var: "string",
	secret: "string",
};

export function generateEnvDts(bindings: BindingDeclaration[]): string {
	if (bindings.length === 0) {
		return `${GENERATED_HEADER}\ninterface Env {}\n`;
	}

	const fields = bindings
		.map((b) => `\t${b.name}: ${BINDING_TYPE_MAP[b.type]};`)
		.join("\n");

	return `${GENERATED_HEADER}\ninterface Env {\n${fields}\n}\n`;
}

export function generateVirtualWorker(opts: {
	plugins: Array<{ name: string; worker?: WorkerContribution }>;
	hasMiddleware: boolean;
	hasRoutes: boolean;
	callbackFiles: string[];
}): string {
	const imports: string[] = [
		'import config from "../stack.config";',
		'import { getPlugin } from "@fcalell/config";',
	];
	const useLines: string[] = [];

	const pluginsWithRuntime = opts.plugins.filter((p) => p.worker?.runtime);

	if (pluginsWithRuntime.length > 0) {
		const firstPlugin = pluginsWithRuntime[0];
		if (firstPlugin?.worker?.runtime) {
			const runtimeImport = firstPlugin.worker.runtime.importFrom.replace(
				/\/runtime$/,
				"",
			);
			imports.push(
				`import { createWorker } from "${runtimeImport}/runtime";`,
			);
		}
	}

	for (const p of pluginsWithRuntime) {
		const runtime = p.worker?.runtime;
		if (!runtime) continue;

		imports.push(
			`import { ${runtime.factory} } from "${runtime.importFrom}";`,
		);

		const callbacks = p.worker?.callbacks;
		const callbackFile = `src/worker/plugins/${p.name}`;
		const hasCallbackFile = opts.callbackFiles.includes(p.name);

		if (callbacks && hasCallbackFile) {
			imports.push(
				`import ${p.name}Callbacks from "../${callbackFile}";`,
			);
			useLines.push(
				`\t.use(${runtime.factory}(getPlugin(config, "${p.name}"), ${p.name}Callbacks))`,
			);
		} else {
			useLines.push(
				`\t.use(${runtime.factory}(getPlugin(config, "${p.name}")))`,
			);
		}
	}

	if (opts.hasMiddleware) {
		imports.push('import middleware from "../src/worker/middleware";');
		useLines.push("\t.use(middleware)");
	}

	if (opts.hasRoutes) {
		imports.push('import * as routes from "../src/worker/routes";');
	}

	const lines: string[] = [GENERATED_HEADER, "", ...imports, ""];

	if (pluginsWithRuntime.length > 0) {
		const handlerArg = opts.hasRoutes ? "routes" : "";
		lines.push(`const worker = createWorker(config)`);
		for (const line of useLines) {
			lines.push(line);
		}
		lines.push(`\t.handler(${handlerArg});`);
		lines.push("");
		lines.push("export type AppRouter = typeof worker._router;");
		lines.push("export default worker;");
	}

	lines.push("");

	return lines.join("\n");
}

export function generateWranglerToml(opts: {
	consumerWrangler: string | null;
	bindings: BindingDeclaration[];
	name?: string;
}): string {
	const lines: string[] = [];

	if (opts.consumerWrangler) {
		lines.push(opts.consumerWrangler.trimEnd());
	} else {
		const name = opts.name ?? "my-app";
		const date = new Date().toISOString().split("T")[0];
		lines.push(`name = "${name}"`);
		lines.push(`compatibility_date = "${date}"`);
		lines.push('main = ".stack/worker.ts"');
	}

	const d1Bindings = opts.bindings.filter((b) => b.type === "d1");
	const r2Bindings = opts.bindings.filter((b) => b.type === "r2");
	const kvBindings = opts.bindings.filter((b) => b.type === "kv");
	const rateLimiters = opts.bindings.filter(
		(b) => b.type === "rate_limiter",
	);
	const services = opts.bindings.filter((b) => b.type === "service");
	const queues = opts.bindings.filter((b) => b.type === "queue");
	const durableObjects = opts.bindings.filter(
		(b) => b.type === "durable_object",
	);
	const vars = opts.bindings.filter(
		(b) => b.type === "var" || b.type === "secret",
	);

	for (const b of d1Bindings) {
		lines.push("");
		lines.push("[[d1_databases]]");
		lines.push(`binding = "${b.name}"`);
		if (b.databaseName) lines.push(`database_name = "${b.databaseName}"`);
		if (b.databaseId) lines.push(`database_id = "${b.databaseId}"`);
	}

	for (const b of r2Bindings) {
		lines.push("");
		lines.push("[[r2_buckets]]");
		lines.push(`binding = "${b.name}"`);
		if (b.bucketName) lines.push(`bucket_name = "${b.bucketName}"`);
	}

	for (const b of kvBindings) {
		lines.push("");
		lines.push("[[kv_namespaces]]");
		lines.push(`binding = "${b.name}"`);
		if (b.kvNamespaceId) lines.push(`id = "${b.kvNamespaceId}"`);
	}

	for (const b of rateLimiters) {
		lines.push("");
		lines.push("[[unsafe.bindings]]");
		lines.push(`name = "${b.name}"`);
		lines.push('type = "ratelimit"');
		if (b.rateLimit) {
			lines.push(`simple = { limit = ${b.rateLimit.limit}, period = ${b.rateLimit.period} }`);
		}
	}

	for (const b of services) {
		lines.push("");
		lines.push("[[services]]");
		lines.push(`binding = "${b.name}"`);
	}

	for (const b of queues) {
		lines.push("");
		lines.push("[[queues.producers]]");
		lines.push(`binding = "${b.name}"`);
	}

	for (const b of durableObjects) {
		lines.push("");
		lines.push("[[durable_objects.bindings]]");
		lines.push(`name = "${b.name}"`);
		if (b.className) lines.push(`class_name = "${b.className}"`);
	}

	if (vars.length > 0) {
		lines.push("");
		lines.push("[vars]");
		for (const b of vars) {
			if (b.type === "var") {
				lines.push(`${b.name} = ""`);
			}
		}
	}

	lines.push("");

	return lines.join("\n");
}

export function generateDevVars(bindings: BindingDeclaration[]): string {
	const secrets = bindings.filter((b) => b.type === "secret");
	if (secrets.length === 0) return "";

	const lines = [
		"# Generated by @fcalell/cli — add your secret values here.",
	];
	for (const b of secrets) {
		lines.push(`${b.name}=${b.devDefault ?? ""}`);
	}
	lines.push("");

	return lines.join("\n");
}

export function collectBindings(
	plugins: Array<{ name: string; cli: CliPlugin; options: unknown }>,
): {
	bindings: BindingDeclaration[];
	collisions: Array<{ name: string; plugins: string[] }>;
} {
	const all: BindingDeclaration[] = [];
	const byName = new Map<string, string[]>();

	for (const p of plugins) {
		const declarations = p.cli.bindings(p.options);
		for (const decl of declarations) {
			all.push(decl);
			const existing = byName.get(decl.name) ?? [];
			existing.push(p.name);
			byName.set(decl.name, existing);
		}
	}

	const collisions: Array<{ name: string; plugins: string[] }> = [];
	for (const [name, pluginNames] of byName) {
		if (pluginNames.length > 1) {
			collisions.push({ name, plugins: pluginNames });
		}
	}

	return { bindings: all, collisions };
}
