import type { BindingDeclaration } from "#config";

const GENERATED_HEADER = "// Generated by @fcalell/cli — do not edit.";

// ── Binding type map ─────────────────────────────────────────────

const BINDING_TYPE_MAP: Record<BindingDeclaration["type"], string> = {
	d1: "D1Database",
	r2: "R2Bucket",
	kv: "KVNamespace",
	queue: "Queue",
	rate_limiter: "RateLimiter",
	durable_object: "DurableObjectNamespace",
	service: "Fetcher",
	var: "string",
	secret: "string",
};

// ── generateEnvDts ───────────────────────────────────────────────

export function generateEnvDts(bindings: BindingDeclaration[]): string {
	const lines: string[] = [GENERATED_HEADER, ""];

	if (bindings.length === 0) {
		lines.push("interface Env {}");
	} else {
		lines.push("interface Env {");
		for (const b of bindings) {
			const tsType = BINDING_TYPE_MAP[b.type] ?? "unknown";
			lines.push(`\t${b.name}: ${tsType};`);
		}
		lines.push("}");
	}

	lines.push("");
	return lines.join("\n");
}

// ── generateWranglerToml ─────────────────────────────────────────

export function generateWranglerToml(opts: {
	consumerWrangler: string | null;
	bindings: BindingDeclaration[];
	name?: string;
}): string {
	const sections: string[] = [];

	if (opts.consumerWrangler) {
		// Replace any existing main line with the correct entry point
		const replaced = opts.consumerWrangler.replace(
			/^main\s*=\s*.*$/m,
			'main = "worker.ts"',
		);
		if (replaced === opts.consumerWrangler) {
			// No main line found — prepend it after the first line
			const consumerLines = opts.consumerWrangler.split("\n");
			const insertIdx = consumerLines.findIndex(
				(l) => l.trim() !== "" && !l.trim().startsWith("#"),
			);
			if (insertIdx >= 0) {
				consumerLines.splice(insertIdx + 1, 0, 'main = "worker.ts"');
			} else {
				consumerLines.push('main = "worker.ts"');
			}
			sections.push(consumerLines.join("\n"));
		} else {
			sections.push(replaced);
		}
	} else {
		const name = opts.name ?? "stack-app";
		const date = new Date().toISOString().split("T")[0];
		sections.push(
			`name = "${name}"\ncompatibility_date = "${date}"\nmain = "worker.ts"`,
		);
	}

	const d1 = opts.bindings.filter((b) => b.type === "d1");
	for (const b of d1) {
		const lines = [
			"",
			"[[d1_databases]]",
			`binding = "${b.name}"`,
			`database_id = "${b.databaseId ?? ""}"`,
		];
		if (b.databaseName) lines.push(`database_name = "${b.databaseName}"`);
		sections.push(lines.join("\n"));
	}

	const kv = opts.bindings.filter((b) => b.type === "kv");
	for (const b of kv) {
		const lines = [
			"",
			"[[kv_namespaces]]",
			`binding = "${b.name}"`,
			`id = "${b.kvNamespaceId ?? ""}"`,
		];
		sections.push(lines.join("\n"));
	}

	const r2 = opts.bindings.filter((b) => b.type === "r2");
	for (const b of r2) {
		const lines = [
			"",
			"[[r2_buckets]]",
			`binding = "${b.name}"`,
			`bucket_name = "${b.bucketName ?? ""}"`,
		];
		sections.push(lines.join("\n"));
	}

	const rateLimiters = opts.bindings.filter((b) => b.type === "rate_limiter");
	for (const b of rateLimiters) {
		const lines = [
			"",
			"[[unsafe.bindings]]",
			`name = "${b.name}"`,
			'type = "ratelimit"',
		];
		if (b.rateLimit) {
			lines.push(`limit = ${b.rateLimit.limit}`);
			lines.push(`period = ${b.rateLimit.period}`);
		}
		sections.push(lines.join("\n"));
	}

	const varsAndSecrets = opts.bindings.filter(
		(b) => b.type === "var" || b.type === "secret",
	);
	if (varsAndSecrets.length > 0) {
		const lines = ["", "[vars]"];
		for (const b of varsAndSecrets) {
			lines.push(`${b.name} = "${b.devDefault ?? ""}"`);
		}
		sections.push(lines.join("\n"));
	}

	return `${sections.join("\n")}\n`;
}

// ── generateDevVars ──────────────────────────────────────────────

export function generateDevVars(bindings: BindingDeclaration[]): string | null {
	const secrets = bindings.filter((b) => b.type === "secret");
	if (secrets.length === 0) return null;

	const lines = secrets.map((b) => `${b.name}=${b.devDefault ?? "changeme"}`);
	return `${lines.join("\n")}\n`;
}

// ── Virtual worker ──────────────────────────────────────────────

interface PluginInfo {
	name: string;
	packageName: string;
	hasRuntime: boolean;
	hasCallbacks: boolean;
	options: Record<string, unknown>;
}

export function hasRuntimeExport(packageName: string): boolean {
	try {
		const pkgPath = require.resolve(`${packageName}/package.json`);
		const pkg = require(pkgPath);
		return !!pkg.exports?.["./runtime"];
	} catch {
		return false;
	}
}

export function serializeOptions(options: Record<string, unknown>): string {
	return JSON.stringify(options, null, "\t");
}

export function generateVirtualWorkerV2(opts: {
	plugins: PluginInfo[];
	hasSchema: boolean;
	hasMiddleware: boolean;
	hasRoutes: boolean;
	domain?: string;
	frontendPort?: number;
	hasFrontend?: boolean;
	hasAuth?: boolean;
}): string {
	const imports: string[] = [];
	const useLines: string[] = [];

	const apiPlugin = opts.plugins.find((p) => p.name === "api");
	if (apiPlugin) {
		imports.push(
			`import createWorker from "${apiPlugin.packageName}/runtime";`,
		);
	}

	for (const p of opts.plugins) {
		if (!p.hasRuntime || p.name === "api") continue;

		const factoryName = `${p.name}Runtime`;
		imports.push(`import ${factoryName} from "${p.packageName}/runtime";`);

		const effectiveOptions = { ...p.options };

		// Auto-configure auth cookie sameSite for cross-origin (frontend + auth)
		if (p.name === "auth" && opts.hasAuth && opts.hasFrontend) {
			effectiveOptions.sameSite = "none";
		}

		const optStr = serializeOptions(effectiveOptions);

		if (p.name === "db" && opts.hasSchema) {
			imports.push('import * as schema from "../src/schema";');
			useLines.push(`\t.use(${factoryName}({ ...${optStr}, schema }))`);
		} else if (p.hasCallbacks) {
			imports.push(
				`import ${p.name}Callbacks from "../src/worker/plugins/${p.name}";`,
			);
			useLines.push(
				`\t.use(${factoryName}({ ...${optStr}, callbacks: ${p.name}Callbacks }))`,
			);
		} else {
			useLines.push(`\t.use(${factoryName}(${optStr}))`);
		}
	}

	if (opts.hasMiddleware) {
		imports.push('import middleware from "../src/worker/middleware";');
		useLines.push("\t.use(middleware)");
	}

	if (opts.hasRoutes) {
		imports.push('import * as routes from "../src/worker/routes";');
	}

	const lines: string[] = [GENERATED_HEADER, "", ...imports, ""];

	if (apiPlugin) {
		const apiOptions: Record<string, unknown> = {};
		if (opts.domain) apiOptions.domain = opts.domain;

		// Auto-configure CORS when frontend plugin is present
		const corsOrigins: string[] = [];
		if (apiPlugin.options.cors) {
			corsOrigins.push(
				...(Array.isArray(apiPlugin.options.cors)
					? apiPlugin.options.cors
					: [apiPlugin.options.cors]),
			);
		}
		if (opts.frontendPort != null) {
			const localOrigin = `http://localhost:${opts.frontendPort}`;
			if (!corsOrigins.includes(localOrigin)) {
				corsOrigins.push(localOrigin);
			}
			if (opts.domain) {
				const domainOrigin = `https://${opts.domain}`;
				if (!corsOrigins.includes(domainOrigin)) {
					corsOrigins.push(domainOrigin);
				}
				const appOrigin = `https://app.${opts.domain}`;
				if (!corsOrigins.includes(appOrigin)) {
					corsOrigins.push(appOrigin);
				}
			}
		}
		if (corsOrigins.length > 0) {
			apiOptions.cors = corsOrigins;
		}

		const handlerArg = opts.hasRoutes ? "routes" : "";
		lines.push(`const worker = createWorker(${serializeOptions(apiOptions)})`);
		for (const line of useLines) {
			lines.push(line);
		}
		lines.push(`\t.handler(${handlerArg});`);
		lines.push("");
		lines.push("export type AppRouter = typeof worker._router;");
		lines.push("export default worker;");
	}

	lines.push("");

	return lines.join("\n");
}
