import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { StackConfig } from "@fcalell/config";

const STACK_DIR = ".stack";
const GENERATED_HEADER = "// Generated by @fcalell/cli — do not edit.";

function ensureStackDir(cwd = process.cwd()): string {
	const dir = join(cwd, STACK_DIR);
	mkdirSync(dir, { recursive: true });
	return dir;
}

export function generateEnvDts(config: StackConfig, cwd = process.cwd()): void {
	const fields: string[] = [];

	if (config.db.dialect === "d1") {
		fields.push("\tDB_MAIN: D1Database;");
	}

	if (config.auth) {
		fields.push("\tAUTH_SECRET: string;");
		fields.push("\tAPP_URL: string;");
	}

	const content = `${GENERATED_HEADER}
interface Env {
${fields.join("\n")}
}
`;

	const dir = ensureStackDir(cwd);
	writeFileSync(join(dir, "env.d.ts"), content);
}

export function generateApiRouteBarrel(cwd = process.cwd()): void {
	const routesDir = join(cwd, "src", "worker", "routes");
	let files: string[];

	try {
		files = readdirSync(routesDir)
			.filter((f) => f.endsWith(".ts") && f !== "index.ts")
			.map((f) => f.replace(/\.ts$/, ""))
			.sort();
	} catch {
		files = [];
	}

	const exports = files.map((f) => `export * from "./${f}";`).join("\n");
	const content = `${GENERATED_HEADER}
${exports ? `${exports}\n` : ""}`;

	writeFileSync(join(routesDir, "index.ts"), content);
}
