import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { generateApiRouteBarrel } from "./generate";

vi.mock("node:fs", () => ({
	mkdirSync: vi.fn(),
	writeFileSync: vi.fn(),
	readdirSync: vi.fn().mockReturnValue([]),
}));

const mockedWriteFileSync = vi.mocked(writeFileSync);
const mockedReaddirSync = vi.mocked(readdirSync);

afterEach(() => {
	vi.restoreAllMocks();
});

describe("generateApiRouteBarrel", () => {
	const cwd = "/my/project";

	it("generates barrel from .ts files excluding index.ts", () => {
		mockedReaddirSync.mockReturnValue([
			"projects.ts",
			"teams.ts",
			"index.ts",
		] as unknown as ReturnType<typeof readdirSync>);

		generateApiRouteBarrel(cwd);

		const content = mockedWriteFileSync.mock.calls[0]?.[1] as string;
		expect(content).toContain('export * from "./projects";');
		expect(content).toContain('export * from "./teams";');
		expect(content).not.toContain('export * from "./index"');
	});

	it("sorts exports alphabetically", () => {
		mockedReaddirSync.mockReturnValue([
			"teams.ts",
			"auth.ts",
		] as unknown as ReturnType<typeof readdirSync>);

		generateApiRouteBarrel(cwd);

		const content = mockedWriteFileSync.mock.calls[0]?.[1] as string;
		const authIndex = content.indexOf("./auth");
		const teamsIndex = content.indexOf("./teams");
		expect(authIndex).toBeLessThan(teamsIndex);
	});

	it("generates empty barrel when only index.ts exists", () => {
		mockedReaddirSync.mockReturnValue(["index.ts"] as unknown as ReturnType<
			typeof readdirSync
		>);

		generateApiRouteBarrel(cwd);

		const content = mockedWriteFileSync.mock.calls[0]?.[1] as string;
		expect(content).not.toContain("export *");
		expect(content).toContain("Generated by @fcalell/cli");
	});

	it("generates empty barrel when routes directory does not exist", () => {
		mockedReaddirSync.mockImplementation(() => {
			throw new Error("ENOENT");
		});

		generateApiRouteBarrel(cwd);

		const content = mockedWriteFileSync.mock.calls[0]?.[1] as string;
		expect(content).not.toContain("export *");
	});

	it("writes to src/worker/routes/index.ts", () => {
		mockedReaddirSync.mockReturnValue(
			[] as unknown as ReturnType<typeof readdirSync>,
		);

		generateApiRouteBarrel(cwd);

		const writePath = mockedWriteFileSync.mock.calls[0]?.[0] as string;
		expect(writePath).toBe(join(cwd, "src", "worker", "routes", "index.ts"));
	});
});
