import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const GENERATED_HEADER = "// Generated by @fcalell/cli — do not edit.";

export function generateApiRouteBarrel(cwd = process.cwd()): void {
	const routesDir = join(cwd, "src", "worker", "routes");
	let files: string[];

	try {
		files = readdirSync(routesDir)
			.filter((f) => f.endsWith(".ts") && f !== "index.ts")
			.map((f) => f.replace(/\.ts$/, ""))
			.sort();
	} catch {
		files = [];
	}

	const exports = files.map((f) => `export * from "./${f}";`).join("\n");
	const content = `${GENERATED_HEADER}\n${exports ? `${exports}\n` : ""}`;

	writeFileSync(join(routesDir, "index.ts"), content);
}
