import {
	type NativeFontEntry,
	nativeFontSchema,
	type ThemeSpec,
	themeSpecSchema,
} from "../types";
import { cssIdent, cssString, cssTokenValue, cssVarName } from "./css";

// Inputs for the `.stack/global.css` derivation. `plugin-native-ui` resolves
// the consumer's `themeTokens` / `fonts` options plus its static base tokens
// and renders the single uniwind entry stylesheet from them.
export interface CodegenGlobalCssPayload {
	themes: ThemeSpec[];
	fonts: NativeFontEntry[];
	// Static, theme-invariant `@theme` tokens, keyed by full `--name`.
	baseTokens: Record<string, string>;
	// `@source` paths (relative to `.stack/`, where global.css lands) telling
	// uniwind where to scan for classNames — the consumer src + this plugin.
	sources: string[];
	// Extra `@import` urls beyond the mandatory tailwindcss + uniwind imports.
	extraImports: string[];
}

const GENERATED_BANNER =
	"/* Generated by @fcalell/plugin-native-ui — do not edit. */\n/* Configure tokens / fonts through stack.config.ts, not this file. */";

// System fallbacks appended after a role's primary family so text still renders
// before the embedded font loads (and on roles the consumer didn't supply).
const ROLE_FALLBACKS: Record<NativeFontEntry["role"], string> = {
	sans: "ui-sans-serif, system-ui, sans-serif",
	mono: "ui-monospace, SFMono-Regular, monospace",
	serif: "ui-serif, Georgia, serif",
};

// First font wins per role — later duplicates are ignored, matching how the
// `--font-<role>` token can only hold one family.
function fontsByRole(fonts: NativeFontEntry[]): NativeFontEntry[] {
	const seen = new Set<NativeFontEntry["role"]>();
	const out: NativeFontEntry[] = [];
	for (const raw of fonts) {
		const font = nativeFontSchema.parse(raw);
		if (seen.has(font.role)) continue;
		seen.add(font.role);
		out.push(font);
	}
	return out;
}

function fontStack(font: NativeFontEntry): string {
	return `${cssString(font.family)}, ${ROLE_FALLBACKS[font.role]}`;
}

// Color tokens are validated as string→string at the option boundary, but Zod
// 4's `z.record` widens its value type to `unknown` on both input and output.
// Re-assert the schema-guaranteed shape in one place rather than casting inline.
function colorEntries(colors: ThemeSpec["colors"]): Array<[string, string]> {
	return Object.entries(colors as Record<string, string>);
}

// Renders the uniwind entry stylesheet:
//   @import 'tailwindcss'; @import 'uniwind';   (mandatory)
//   @source ...                                  (className scan roots)
//   @theme { base tokens, font tokens, default-theme colors }
//   @layer theme { :root { @variant <name> { color overrides } } }
//
// Re-validates every contribution at render time (defense-in-depth): the option
// schema rejects garbage on entry, but anything reaching here invalid is a bug
// in the contributing config and we want a loud error, not corrupt CSS.
export function aggregateGlobalCss(payload: CodegenGlobalCssPayload): string {
	const lines: string[] = [GENERATED_BANNER, ""];

	lines.push("@import 'tailwindcss';");
	lines.push("@import 'uniwind';");
	for (const imp of payload.extraImports) {
		lines.push(`@import ${cssString(imp)};`);
	}
	lines.push("");

	for (const src of payload.sources) {
		lines.push(`@source ${cssString(src)};`);
	}
	if (payload.sources.length > 0) lines.push("");

	// Re-validate every theme (throws on bad input). We iterate the typed input
	// array rather than the parse result so `colors` stays Record<string,string>
	// — Zod 4's record output type widens values to `unknown` through `.parse`.
	for (const theme of payload.themes) themeSpecSchema.parse(theme);
	const themes = payload.themes;
	const defaultTheme = themes.find((t) => t.default) ?? themes[0];

	// ── @theme: static tokens + font tokens + default-theme colors ──
	const themeBody: string[] = [];
	for (const [name, value] of Object.entries(payload.baseTokens)) {
		themeBody.push(`\t${cssVarName(name)}: ${cssTokenValue(value)};`);
	}
	for (const font of fontsByRole(payload.fonts)) {
		themeBody.push(`\t--font-${cssIdent(font.role)}: ${fontStack(font)};`);
	}
	if (defaultTheme) {
		for (const [key, value] of colorEntries(defaultTheme.colors)) {
			themeBody.push(`\t--color-${cssIdent(key)}: ${cssTokenValue(value)};`);
		}
	}
	lines.push("@theme {");
	lines.push(...themeBody);
	lines.push("}");
	lines.push("");

	// ── @layer theme: every theme as a switchable @variant ──
	lines.push("@layer theme {");
	lines.push("\t:root {");
	for (const theme of themes) {
		lines.push(`\t\t@variant ${cssIdent(theme.name)} {`);
		for (const [key, value] of colorEntries(theme.colors)) {
			lines.push(`\t\t\t--color-${cssIdent(key)}: ${cssTokenValue(value)};`);
		}
		lines.push("\t\t}");
	}
	lines.push("\t}");
	lines.push("}");

	return `${lines.join("\n")}\n`;
}
