import type { ResolvedTheme } from "@fcalell/ui-core/derive";
import type { NativeFontEntry } from "../types";
import { cssIdent, cssString, cssTokenValue, cssVarName } from "./css";
import { modeBlocks, shadowBlocks, themeDeclarations } from "./theme";

// Inputs for the `.stack/global.css` derivation. `plugin-native-ui` resolves
// the consumer's `theme` option through ui-core's `deriveTheme` and renders
// the single uniwind entry stylesheet from it.
export interface CodegenGlobalCssPayload {
	resolved: ResolvedTheme;
	fonts: NativeFontEntry[];
	// `@source` paths (relative to `.stack/`, where global.css lands) telling
	// uniwind where to scan for classNames — the consumer src, this plugin, and
	// ui-core (the matrix cell strings live there).
	sources: string[];
	// Extra `@import` urls beyond the mandatory tailwindcss + uniwind imports.
	extraImports: string[];
}

const GENERATED_BANNER =
	"/* Generated by @fcalell/plugin-native-ui — do not edit. */\n/* Configure tokens / fonts through stack.config.ts, not this file. */";

// Renders the uniwind entry stylesheet:
//   @import 'tailwindcss'; @import 'uniwind';    (mandatory)
//   @source ...                                   (className scan roots)
//   @theme { resets, scales, colors, font tokens }
//   @utility shadow-<level> { box-shadow: … }     (× 3)
//   @layer theme { :root { @variant light|dark { color overrides } } }
//
// Every name and value crosses the render boundary through cssVarName /
// cssIdent / cssTokenValue (defense-in-depth): the option schema rejects
// garbage on entry, but anything reaching here invalid is a bug in the
// contributing config and we want a loud error, not corrupt CSS.
export function aggregateGlobalCss(payload: CodegenGlobalCssPayload): string {
	const lines: string[] = [GENERATED_BANNER, ""];

	lines.push("@import 'tailwindcss';");
	lines.push("@import 'uniwind';");
	for (const imp of payload.extraImports) {
		lines.push(`@import ${cssString(imp)};`);
	}
	lines.push("");

	for (const src of payload.sources) {
		lines.push(`@source ${cssString(src)};`);
	}
	if (payload.sources.length > 0) lines.push("");

	lines.push("@theme {");
	const declarations = themeDeclarations(payload.resolved, payload.fonts);
	for (const [name, value] of Object.entries(declarations)) {
		lines.push(`\t${cssVarName(name)}: ${cssTokenValue(value)};`);
	}
	lines.push("}");
	lines.push("");

	for (const [name, value] of shadowBlocks(payload.resolved)) {
		lines.push(`@utility ${cssIdent(name)} {`);
		lines.push(`\tbox-shadow: ${cssTokenValue(value)};`);
		lines.push("}");
		lines.push("");
	}

	lines.push("@layer theme {");
	lines.push("\t:root {");
	for (const [mode, colors] of modeBlocks(payload.resolved)) {
		lines.push(`\t\t@variant ${cssIdent(mode)} {`);
		for (const [token, value] of Object.entries(colors)) {
			lines.push(`\t\t\t--color-${cssIdent(token)}: ${cssTokenValue(value)};`);
		}
		lines.push("\t\t}");
	}
	lines.push("\t}");
	lines.push("}");

	return `${lines.join("\n")}\n`;
}
