import { describe, expect, it } from "vitest";
import { generateEnvDts } from "@fcalell/cli/codegen";
import type { BindingDeclaration } from "@fcalell/config";

describe("generateEnvDts", () => {
	it("D1 binding produces D1Database type", () => {
		const result = generateEnvDts([
			{ name: "DB_MAIN", type: "d1", databaseId: "test-id" },
		]);

		expect(result).toContain("DB_MAIN: D1Database;");
	});

	it("secret binding produces string type", () => {
		const result = generateEnvDts([
			{ name: "AUTH_SECRET", type: "secret" },
		]);

		expect(result).toContain("AUTH_SECRET: string;");
	});

	it("rate limiter binding produces RateLimiter type", () => {
		const result = generateEnvDts([
			{
				name: "RATE_LIMITER_IP",
				type: "rate_limiter",
				rateLimit: { limit: 100, period: 60 },
			},
		]);

		expect(result).toContain("RATE_LIMITER_IP: RateLimiter;");
	});

	it("multiple bindings produce correct interface", () => {
		const bindings: BindingDeclaration[] = [
			{ name: "DB_MAIN", type: "d1", databaseId: "test-id" },
			{ name: "AUTH_SECRET", type: "secret" },
			{ name: "APP_URL", type: "secret" },
			{
				name: "RATE_LIMITER_IP",
				type: "rate_limiter",
				rateLimit: { limit: 100, period: 60 },
			},
			{
				name: "RATE_LIMITER_EMAIL",
				type: "rate_limiter",
				rateLimit: { limit: 5, period: 300 },
			},
		];

		const result = generateEnvDts(bindings);

		expect(result).toContain("interface Env {");
		expect(result).toContain("DB_MAIN: D1Database;");
		expect(result).toContain("AUTH_SECRET: string;");
		expect(result).toContain("APP_URL: string;");
		expect(result).toContain("RATE_LIMITER_IP: RateLimiter;");
		expect(result).toContain("RATE_LIMITER_EMAIL: RateLimiter;");
	});

	it("empty bindings produce minimal interface", () => {
		const result = generateEnvDts([]);

		expect(result).toContain("interface Env {}");
		expect(result).not.toContain(": D1Database");
		expect(result).not.toContain(": string");
		expect(result).not.toContain(": RateLimiter");
	});

	it("all known binding types map to correct TypeScript types", () => {
		const allTypes: BindingDeclaration[] = [
			{ name: "A", type: "d1" },
			{ name: "B", type: "r2" },
			{ name: "C", type: "kv" },
			{ name: "D", type: "queue" },
			{ name: "E", type: "rate_limiter" },
			{ name: "F", type: "durable_object" },
			{ name: "G", type: "service" },
			{ name: "H", type: "var" },
			{ name: "I", type: "secret" },
		];

		const result = generateEnvDts(allTypes);

		expect(result).toContain("A: D1Database;");
		expect(result).toContain("B: R2Bucket;");
		expect(result).toContain("C: KVNamespace;");
		expect(result).toContain("D: Queue;");
		expect(result).toContain("E: RateLimiter;");
		expect(result).toContain("F: DurableObjectNamespace;");
		expect(result).toContain("G: Fetcher;");
		expect(result).toContain("H: string;");
		expect(result).toContain("I: string;");
	});

	it("output includes the generated header comment", () => {
		const result = generateEnvDts([{ name: "DB", type: "d1" }]);
		expect(result).toContain("Generated by @fcalell/cli");
	});
});
