import { readdirSync } from "node:fs";
import { join } from "node:path";

const GENERATED_HEADER = "// Generated by @fcalell/cli — do not edit.";

export function generateRouteBarrel(cwd: string): string {
	const routesDir = join(cwd, "src", "worker", "routes");
	let files: string[];

	try {
		files = readdirSync(routesDir)
			.filter((f) => f.endsWith(".ts") && f !== "index.ts")
			.map((f) => f.replace(/\.ts$/, ""))
			.sort();
	} catch {
		files = [];
	}

	const exports = files.map((f) => `export * from "./${f}";`).join("\n");
	return `${GENERATED_HEADER}\n${exports ? `${exports}\n` : ""}`;
}
