import { readdirSync } from "node:fs";
import { join } from "node:path";

const GENERATED_HEADER = "// Generated by @fcalell/cli — do not edit.";

// Conventions for the route directory layout:
//   - Flat: `src/worker/routes/<name>.ts(x)` — one oRPC procedure file per
//     name. Subdirectories are intentionally ignored; consumers who want
//     nested namespaces emit their own barrel and import it explicitly.
//   - `index.ts` / `index.tsx` IS the barrel. Excluded so the barrel doesn't
//     re-export itself.
//   - `.test.ts(x)` and `.d.ts` files are excluded — tests poison the
//     runtime barrel, declarations have no runtime export.
//   - A name colliding across `.ts` and `.tsx` (e.g. both `users.ts` and
//     `users.tsx`) is ambiguous: TS module resolution picks one
//     non-deterministically and the emitted `export * from "./users"`
//     would silently swallow the other. Throw at codegen so the consumer
//     fixes the conflict.
function isRouteFile(file: string): boolean {
	if (!(file.endsWith(".ts") || file.endsWith(".tsx"))) return false;
	if (file.endsWith(".d.ts")) return false;
	if (file.endsWith(".test.ts") || file.endsWith(".test.tsx")) return false;
	if (file === "index.ts" || file === "index.tsx") return false;
	return true;
}

function basenameWithoutExt(file: string): string {
	return file.replace(/\.tsx?$/, "");
}

export function generateRouteBarrel(cwd: string): string {
	const routesDir = join(cwd, "src", "worker", "routes");
	let entries: string[];

	try {
		// `withFileTypes: false` (the default) — we only want top-level
		// regular files. Nested directories appear here as plain names and
		// are filtered out by the extension check.
		entries = readdirSync(routesDir).filter(isRouteFile);
	} catch {
		entries = [];
	}

	// Detect ambiguous basenames before sorting/dedupe collapses them.
	const byBasename = new Map<string, string[]>();
	for (const entry of entries) {
		const base = basenameWithoutExt(entry);
		const bucket = byBasename.get(base);
		if (bucket) bucket.push(entry);
		else byBasename.set(base, [entry]);
	}
	const collisions = [...byBasename.entries()].filter(
		([, files]) => files.length > 1,
	);
	if (collisions.length > 0) {
		const detail = collisions
			.map(([base, files]) => `${base} (${files.sort().join(" + ")})`)
			.join(", ");
		throw new Error(
			`generateRouteBarrel: ambiguous route basename(s) — ${detail}. ` +
				"Pick one of .ts or .tsx per route name.",
		);
	}

	const exports = [...byBasename.keys()]
		.sort()
		.map((name) => `export * from "./${name}";`)
		.join("\n");

	return `${GENERATED_HEADER}\n${exports ? `${exports}\n` : ""}`;
}

// Returns true when there is at least one routable file in the consumer's
// `src/worker/routes` directory. The plugin's source slot uses this to
// short-circuit emission — there's no point writing a header-only barrel
// when no routes exist (and downstream imports have nothing to consume).
export function hasRoutableFiles(cwd: string): boolean {
	const routesDir = join(cwd, "src", "worker", "routes");
	try {
		return readdirSync(routesDir).some(isRouteFile);
	} catch {
		return false;
	}
}
