import { readdirSync } from "node:fs";
import { join } from "node:path";
import type { CliPlugin, GeneratedFile } from "@fcalell/config/plugin";
import type { ApiOptions } from "./index";

const GENERATED_HEADER = "// Generated by @fcalell/cli — do not edit.";

const WRANGLER_TEMPLATE = (name: string, databaseId: string) =>
	`name = "${name}"
compatibility_date = "${new Date().toISOString().split("T")[0]}"
main = "src/worker/index.ts"

[[d1_databases]]
binding = "DB_MAIN"
database_name = "${name}-db"
database_id = "${databaseId}"
`;

function generateRouteBarrel(cwd: string): string {
	const routesDir = join(cwd, "src", "worker", "routes");
	let files: string[];

	try {
		files = readdirSync(routesDir)
			.filter((f) => f.endsWith(".ts") && f !== "index.ts")
			.map((f) => f.replace(/\.ts$/, ""))
			.sort();
	} catch {
		files = [];
	}

	const exports = files.map((f) => `export * from "./${f}";`).join("\n");
	return `${GENERATED_HEADER}\n${exports ? `${exports}\n` : ""}`;
}

const plugin: CliPlugin<ApiOptions> = {
	name: "api",
	label: "API",

	detect(ctx) {
		return ctx.hasPlugin("api");
	},

	async prompt(_ctx) {
		return {};
	},

	async scaffold(ctx, _answers) {
		await ctx.ensureDir("src/worker/routes");

		const dbOptions = ctx.getPluginOptions<{
			dialect: string;
			databaseId?: string;
		}>("db");

		if (dbOptions?.dialect === "d1") {
			const wranglerContent = WRANGLER_TEMPLATE(
				"my-app",
				dbOptions.databaseId ?? "YOUR_D1_DATABASE_ID",
			);
			await ctx.writeIfMissing("wrangler.toml", wranglerContent);
		}

		ctx.addDependencies({
			"@fcalell/plugin-api": "workspace:*",
		});
		ctx.addDevDependencies({
			wrangler: "^4.14.0",
		});
		ctx.addToGitignore(".wrangler", ".stack");
	},

	bindings(_options) {
		return [];
	},

	async generate(ctx): Promise<GeneratedFile[]> {
		const files: GeneratedFile[] = [];

		const barrelContent = generateRouteBarrel(ctx.cwd);
		files.push({
			path: "src/worker/routes/index.ts",
			content: barrelContent,
		});

		return files;
	},

	worker: {
		runtime: {
			importFrom: "@fcalell/plugin-api/runtime",
			factory: "createWorker",
		},
		routes: true,
		middleware: true,
	},

	async dev(ctx) {
		const port = ctx.getPort("api");

		return {
			processes: [
				{
					name: "api",
					command: "npx",
					args: ["wrangler", "dev", "--port", String(port)],
					defaultPort: 8787,
					readyPattern: /Ready on/,
					color: "yellow",
				},
			],
			watchers: [
				{
					paths: ["src/worker/routes"],
					ignore: ["**/index.ts"],
					debounce: 300,
					async onChange(event) {
						if (event.type === "add" || event.type === "unlink") {
							const barrelContent = generateRouteBarrel(ctx.cwd);
							await ctx.writeFile("src/worker/routes/index.ts", barrelContent);
							ctx.log.info("Route barrel regenerated");
						}
					},
				},
			],
			banner: [`API: http://localhost:${port}`],
		};
	},

	async build(_ctx) {
		return {
			async postBuild() {
				// TODO: run wrangler build for the worker
			},
		};
	},

	async deploy(ctx) {
		ctx.log.info("Deploying API worker...");
		// TODO: run wrangler deploy
	},
};

export default plugin;
