import type { DevContext, PluginContext } from "@fcalell/config/plugin";
import { describe, expect, it, vi } from "vitest";
import plugin from "./cli";

function mockCtx(overrides?: Partial<PluginContext>): PluginContext {
	return {
		cwd: "/tmp/test",
		config: null,
		hasPlugin: () => false,
		getPluginOptions: () => undefined,
		writeFile: vi.fn(),
		writeIfMissing: vi.fn().mockResolvedValue(true),
		ensureDir: vi.fn(),
		fileExists: vi.fn().mockResolvedValue(false),
		readFile: vi.fn().mockResolvedValue(""),
		addDependencies: vi.fn(),
		addDevDependencies: vi.fn(),
		addToGitignore: vi.fn(),
		addPluginToConfig: vi.fn(),
		removePluginFromConfig: vi.fn(),
		prompt: {
			text: vi.fn(),
			confirm: vi.fn(),
			select: vi.fn(),
			multiselect: vi.fn(),
		},
		log: {
			info: vi.fn(),
			warn: vi.fn(),
			success: vi.fn(),
			error: vi.fn(),
		},
		...overrides,
	};
}

function mockDevCtx(overrides?: Partial<DevContext>): DevContext {
	return {
		...mockCtx(),
		getPort: () => 8787,
		...overrides,
	};
}

describe("api cli plugin", () => {
	it("has correct name and label", () => {
		expect(plugin.name).toBe("api");
		expect(plugin.label).toBe("API");
	});

	describe("detect", () => {
		it("returns true when api plugin is present", () => {
			const ctx = mockCtx({ hasPlugin: (name) => name === "api" });
			expect(plugin.detect(ctx)).toBe(true);
		});

		it("returns false when api plugin is absent", () => {
			const ctx = mockCtx({ hasPlugin: () => false });
			expect(plugin.detect(ctx)).toBe(false);
		});
	});

	describe("bindings", () => {
		it("returns empty array", () => {
			const bindings = plugin.bindings({ prefix: "/rpc" });
			expect(bindings).toEqual([]);
		});

		it("returns empty array with no options", () => {
			const bindings = plugin.bindings({});
			expect(bindings).toEqual([]);
		});
	});

	describe("scaffold", () => {
		it("creates routes directory", async () => {
			const ctx = mockCtx();
			await plugin.scaffold(ctx, {});

			expect(ctx.ensureDir).toHaveBeenCalledWith("src/worker/routes");
		});

		it("adds api dependency", async () => {
			const ctx = mockCtx();
			await plugin.scaffold(ctx, {});

			expect(ctx.addDependencies).toHaveBeenCalledWith({
				"@fcalell/plugin-api": "workspace:*",
			});
		});

		it("adds wrangler dev dependency", async () => {
			const ctx = mockCtx();
			await plugin.scaffold(ctx, {});

			expect(ctx.addDevDependencies).toHaveBeenCalledWith(
				expect.objectContaining({
					wrangler: expect.any(String),
				}),
			);
		});

		it("adds .wrangler and .stack to gitignore", async () => {
			const ctx = mockCtx();
			await plugin.scaffold(ctx, {});

			expect(ctx.addToGitignore).toHaveBeenCalledWith(".wrangler", ".stack");
		});

		it("creates wrangler.toml when db is D1", async () => {
			const ctx = mockCtx({
				hasPlugin: (name) => name === "db",
				getPluginOptions: ((name: string) => {
					if (name === "db") return { dialect: "d1", databaseId: "abc-123" };
					return undefined;
				}) as PluginContext["getPluginOptions"],
			});
			await plugin.scaffold(ctx, {});

			expect(ctx.writeIfMissing).toHaveBeenCalledWith(
				"wrangler.toml",
				expect.stringContaining("abc-123"),
			);
		});

		it("skips wrangler.toml when db is sqlite", async () => {
			const ctx = mockCtx({
				hasPlugin: (name) => name === "db",
				getPluginOptions: ((name: string) => {
					if (name === "db")
						return { dialect: "sqlite", path: "./data/app.sqlite" };
					return undefined;
				}) as PluginContext["getPluginOptions"],
			});
			await plugin.scaffold(ctx, {});

			expect(ctx.writeIfMissing).not.toHaveBeenCalledWith(
				"wrangler.toml",
				expect.any(String),
			);
		});
	});

	describe("generate", () => {
		it("returns route barrel file", async () => {
			const ctx = mockCtx();
			const files = await plugin.generate(ctx);

			expect(files).toHaveLength(1);
			expect(files[0]?.path).toBe("src/worker/routes/index.ts");
			expect(files[0]?.content).toContain("Generated by @fcalell/cli");
		});
	});

	describe("worker", () => {
		it("declares runtime contribution", () => {
			expect(plugin.worker?.runtime).toEqual({
				importFrom: "@fcalell/plugin-api/runtime",
				factory: "createWorker",
			});
		});

		it("declares routes and middleware", () => {
			expect(plugin.worker?.routes).toBe(true);
			expect(plugin.worker?.middleware).toBe(true);
		});
	});

	describe("dev", () => {
		async function callDev(ctx: DevContext) {
			expect(plugin.dev).toBeDefined();
			// biome-ignore lint/style/noNonNullAssertion: dev is asserted above
			return plugin.dev!(ctx);
		}

		it("returns wrangler process with correct port", async () => {
			const ctx = mockDevCtx({ getPort: () => 9000 });
			const contribution = await callDev(ctx);

			expect(contribution.processes).toHaveLength(1);
			expect(contribution.processes?.[0]?.name).toBe("api");
			expect(contribution.processes?.[0]?.args).toContain("9000");
		});

		it("includes route watcher", async () => {
			const ctx = mockDevCtx();
			const contribution = await callDev(ctx);

			expect(contribution.watchers).toHaveLength(1);
			expect(contribution.watchers?.[0]?.paths).toEqual(["src/worker/routes"]);
		});

		it("includes banner with port", async () => {
			const ctx = mockDevCtx({ getPort: () => 8787 });
			const contribution = await callDev(ctx);

			expect(contribution.banner).toEqual(["API: http://localhost:8787"]);
		});
	});
});
