import type { RegisterContext } from "@fcalell/cli";
import {
	createEventBus,
	Dev,
	Generate,
	Init,
	Remove,
} from "@fcalell/cli/events";
import { describe, expect, it, vi } from "vitest";
import { type ApiOptions, api } from "./index";

function createMockCtx(
	overrides: Partial<RegisterContext<ApiOptions>> & { options: ApiOptions },
): RegisterContext<ApiOptions> {
	return {
		cwd: "/tmp/test",
		hasPlugin: () => false,
		readFile: vi.fn(async () => ""),
		fileExists: vi.fn(async () => false),
		log: {
			info: vi.fn(),
			warn: vi.fn(),
			success: vi.fn(),
			error: vi.fn(),
		},
		prompt: {
			text: vi.fn(async () => ""),
			confirm: vi.fn(async () => false),
			// biome-ignore lint/suspicious/noExplicitAny: mock return type
			select: vi.fn(async () => undefined as any),
			multiselect: vi.fn(async () => []),
		},
		...overrides,
	};
}

describe("api config factory", () => {
	it("returns PluginConfig with __plugin: 'api'", () => {
		const config = api({});
		expect(config.__plugin).toBe("api");
	});

	it("default prefix is /rpc", () => {
		const config = api({});
		expect(config.options.prefix).toBe("/rpc");
	});

	it("custom prefix is preserved", () => {
		const config = api({ prefix: "/api" });
		expect(config.options.prefix).toBe("/api");
	});

	it("throws when prefix doesn't start with /", () => {
		// @ts-expect-error testing runtime validation
		expect(() => api({ prefix: "rpc" })).toThrow(
			"api: prefix must start with /",
		);
	});

	it("throws when cors is invalid type", () => {
		// @ts-expect-error testing runtime validation
		expect(() => api({ cors: 123 })).toThrow(
			"api: cors must be a string or array of strings",
		);
	});

	it("accepts cors as string", () => {
		const config = api({ cors: "https://example.com" });
		expect(config.options.cors).toBe("https://example.com");
	});

	it("accepts cors as string array", () => {
		const origins = ["https://a.com", "https://b.com"];
		const config = api({ cors: origins });
		expect(config.options.cors).toEqual(origins);
	});

	it("accepts empty options (all defaults)", () => {
		const config = api({});
		expect(config.options.prefix).toBe("/rpc");
		expect(config.options.cors).toBeUndefined();
		expect(config.options.domain).toBeUndefined();
	});

	it("custom domain is preserved", () => {
		const config = api({ domain: "api.example.com" });
		expect(config.options.domain).toBe("api.example.com");
	});
});

describe("api.name", () => {
	it("is 'api'", () => {
		expect(api.name).toBe("api");
	});
});

describe("api.cli", () => {
	it("has correct name and label", () => {
		expect(api.cli.name).toBe("api");
		expect(api.cli.label).toBe("API");
	});
});

describe("api register", () => {
	it("pushes scaffold files on Init.Scaffold", async () => {
		const bus = createEventBus();
		const ctx = createMockCtx({
			options: { prefix: "/rpc" },
		});
		api.cli.register(ctx, bus, api.events);

		const scaffold = await bus.emit(Init.Scaffold, {
			files: [],
			dependencies: {},
			devDependencies: {},
			gitignore: [],
		});

		expect(scaffold.files).toContainEqual(
			expect.objectContaining({
				path: "wrangler.toml",
			}),
		);
		expect(scaffold.dependencies["@fcalell/plugin-api"]).toBe("workspace:*");
		expect(scaffold.devDependencies.wrangler).toBeDefined();
		expect(scaffold.gitignore).toContain(".wrangler");
		expect(scaffold.gitignore).toContain(".stack");
	});

	it("pushes route barrel on Generate", async () => {
		const bus = createEventBus();
		const ctx = createMockCtx({
			options: { prefix: "/rpc" },
		});
		api.cli.register(ctx, bus, api.events);

		const gen = await bus.emit(Generate, { files: [], bindings: [] });

		expect(gen.files).toContainEqual(
			expect.objectContaining({
				path: "src/worker/routes/index.ts",
				content: expect.stringContaining("Generated by @fcalell/cli"),
			}),
		);
	});

	it("pushes cleanup info on Remove", async () => {
		const bus = createEventBus();
		const ctx = createMockCtx({
			options: { prefix: "/rpc" },
		});
		api.cli.register(ctx, bus, api.events);

		const removal = await bus.emit(Remove, {
			files: [],
			dependencies: [],
		});

		expect(removal.files).toContain("src/worker/routes/");
		expect(removal.dependencies).toContain("@fcalell/plugin-api");
		expect(removal.dependencies).toContain("wrangler");
	});

	it("pushes wrangler process and route watcher on Dev.Start", async () => {
		const bus = createEventBus();
		const ctx = createMockCtx({
			options: { prefix: "/rpc" },
		});
		api.cli.register(ctx, bus, api.events);

		const devStart = await bus.emit(Dev.Start, {
			processes: [],
			watchers: [],
		});

		expect(devStart.processes).toHaveLength(1);
		expect(devStart.processes[0]?.name).toBe("api");
		expect(devStart.processes[0]?.command).toBe("npx");
		expect(devStart.processes[0]?.args).toContain("wrangler");

		expect(devStart.watchers).toHaveLength(1);
		expect(devStart.watchers[0]?.name).toBe("routes");
		expect(devStart.watchers[0]?.paths).toBe("src/worker/routes/**");
	});
});
