import {
	createEventBus,
	Dev,
	Generate,
	Init,
	Remove,
} from "@fcalell/cli/events";
import { createMockCtx } from "@fcalell/cli/testing";
import { describe, expect, it } from "vitest";
import { type ApiOptions, api } from "./index";

describe("api config factory", () => {
	it("returns PluginConfig with __plugin: 'api'", () => {
		const config = api({});
		expect(config.__plugin).toBe("api");
	});

	it("default prefix is /rpc", () => {
		const config = api({});
		expect(config.options.prefix).toBe("/rpc");
	});

	it("custom prefix is preserved", () => {
		const config = api({ prefix: "/api" });
		expect(config.options.prefix).toBe("/api");
	});

	it("throws when prefix doesn't start with /", () => {
		expect(() => api({ prefix: "rpc" })).toThrow(
			"api: prefix must start with /",
		);
	});

	it("accepts empty options (all defaults)", () => {
		const config = api({});
		expect(config.options.prefix).toBe("/rpc");
	});
});

describe("api.name", () => {
	it("is 'api'", () => {
		expect(api.name).toBe("api");
	});
});

describe("api.cli", () => {
	it("has correct name and label", () => {
		expect(api.cli.name).toBe("api");
		expect(api.cli.label).toBe("API");
	});
});

describe("api register", () => {
	it("contributes deps/devDeps/gitignore on Init.Scaffold (no wrangler scaffold)", async () => {
		const bus = createEventBus();
		const ctx = createMockCtx<ApiOptions>({
			options: { prefix: "/rpc" },
		});
		api.cli.register(ctx, bus, api.events);

		const scaffold = await bus.emit(Init.Scaffold, {
			files: [],
			dependencies: {},
			devDependencies: {},
			gitignore: [],
		});

		// wrangler.toml is no longer scaffolded — the CLI's aggregateWrangler
		// handles the missing consumer file directly.
		expect(scaffold.files.some((f) => f.target === "wrangler.toml")).toBe(
			false,
		);
		expect(scaffold.dependencies["@fcalell/plugin-api"]).toBe("workspace:*");
		expect(scaffold.devDependencies.wrangler).toBeDefined();
		expect(scaffold.gitignore).toContain(".wrangler");
		expect(scaffold.gitignore).toContain(".stack");
	});

	it("pushes route barrel on Generate", async () => {
		const bus = createEventBus();
		const ctx = createMockCtx<ApiOptions>({
			options: { prefix: "/rpc" },
		});
		api.cli.register(ctx, bus, api.events);

		const gen = await bus.emit(Generate, { files: [], postWrite: [] });

		expect(gen.files).toContainEqual(
			expect.objectContaining({
				path: "src/worker/routes/index.ts",
				content: expect.stringContaining("Generated by @fcalell/cli"),
			}),
		);
	});

	it("pushes cleanup info on Remove", async () => {
		const bus = createEventBus();
		const ctx = createMockCtx<ApiOptions>({
			options: { prefix: "/rpc" },
		});
		api.cli.register(ctx, bus, api.events);

		const removal = await bus.emit(Remove, {
			files: [],
			dependencies: [],
			devDependencies: [],
		});

		expect(removal.files).toContain("src/worker/routes/");
		expect(removal.dependencies).toContain("@fcalell/plugin-api");
		expect(removal.devDependencies).toContain("wrangler");
	});

	it("claims worker base on api.events.Worker with createWorker() call", async () => {
		const bus = createEventBus();
		const ctx = createMockCtx<ApiOptions>({
			options: { prefix: "/rpc" },
		});
		api.cli.register(ctx, bus, api.events);

		const worker = await bus.emit(api.events.Worker, {
			imports: [],
			base: null,
			pluginRuntimes: [],
			middlewareChain: [],
			handler: null,
			cors: ["https://example.com"],
		});

		expect(worker.base).not.toBeNull();
		expect(worker.base?.kind).toBe("call");
		if (worker.base?.kind === "call") {
			expect(worker.base.callee).toEqual({
				kind: "identifier",
				name: "createWorker",
			});
			const firstArg = worker.base.args[0];
			expect(firstArg?.kind).toBe("object");
			if (firstArg?.kind === "object") {
				const keys = firstArg.properties.map((prop) => prop.key);
				expect(keys).toContain("cors");
			}
		}
		expect(worker.imports).toContainEqual({
			source: "@fcalell/plugin-api/runtime",
			default: "createWorker",
		});
	});

	it("throws on api.events.Worker when another plugin already claimed base", async () => {
		const bus = createEventBus();
		const ctx = createMockCtx<ApiOptions>({
			options: { prefix: "/rpc" },
		});
		api.cli.register(ctx, bus, api.events);

		await expect(
			bus.emit(api.events.Worker, {
				imports: [],
				base: {
					kind: "call",
					callee: { kind: "identifier", name: "other" },
					args: [],
				},
				pluginRuntimes: [],
				middlewareChain: [],
				handler: null,
				cors: [],
			}),
		).rejects.toThrow(/cannot claim the worker root/);
	});

	it("pushes wrangler process and route watcher on Dev.Start", async () => {
		const bus = createEventBus();
		const ctx = createMockCtx<ApiOptions>({
			options: { prefix: "/rpc" },
		});
		api.cli.register(ctx, bus, api.events);

		const devStart = await bus.emit(Dev.Start, {
			processes: [],
			watchers: [],
		});

		expect(devStart.processes).toHaveLength(1);
		expect(devStart.processes[0]?.name).toBe("api");
		expect(devStart.processes[0]?.command).toBe("npx");
		expect(devStart.processes[0]?.args).toContain("wrangler");

		expect(devStart.watchers).toHaveLength(1);
		expect(devStart.watchers[0]?.name).toBe("routes");
		expect(devStart.watchers[0]?.paths).toBe("src/worker/routes/**");
	});
});
