// The web overlay allowlist: every class the components spell outside a
// matrix cell, other than a state variant over a contract token, spelled out
// as a second opinion. Check b5 asserts it equals the set swept from
// `src/ui/components`, so a component edit that adds or drops an overlay
// class fails until this list moves with it. Each entry is a board string
// less its cell, verbatim from `atoms-overlays.md`.
export const OVERLAYS: readonly string[] = [
	"max-w-measure",
	// Button, IconButton
	"relative",
	"absolute",
	"inset-0",
	"flex",
	"opacity-0",
	"text-ink-disabled",
	"shrink-0",
	"flex-col",
	"items-start",
	"gap-pair",
	// Status, Chip
	"inline-flex",
	"items-center",
	"justify-center",
	"min-w-0",
	"shrink-0",
	"truncate",
	"focus-visible:-outline-offset-2",
	// Input, TextArea, InputOtp
	"flex",
	"flex-col",
	"items-center",
	"justify-center",
	"justify-end",
	"min-w-0",
	"shrink-0",
	"truncate",
	"block",
	"w-full",
	"relative",
	"absolute",
	"inset-0",
	"opacity-0",
	"text-center",
	"outline-none",
	"placeholder:text-ink-meta",
	"bg-fill-disabled",
	"text-ink-disabled",
	"has-focus-visible:outline-2",
	"has-focus-visible:outline-offset-2",
	"has-focus-visible:outline-ring",
	"not-has-[button:focus-visible]:has-focus-visible:outline-2",
	"not-has-[button:focus-visible]:has-focus-visible:outline-offset-2",
	"not-has-[button:focus-visible]:has-focus-visible:outline-ring",
	"field-sizing-content",
	"peer-focus-visible:outline-2",
	"peer-focus-visible:outline-offset-2",
	"peer-focus-visible:outline-ring",
	"gap-pair",
	"gap-inside",
	"not-has-[button:hover]:hover:border-edge-hover",
	// Select
	"flex",
	"flex-col",
	"items-center",
	"min-w-0",
	"truncate",
	"bg-fill-disabled",
	"text-ink-disabled",
	"w-(--anchor-width)",
	"data-popup-open:outline-2",
	"data-popup-open:outline-offset-2",
	"data-popup-open:outline-ring",
	"px-control-x",
	"pt-pair",
	"outline-none",
	"shrink-0",
	"text-ink-body",
	// Slider, Switch, Checkbox
	"flex",
	"flex-col",
	"justify-center",
	"items-center",
	"justify-between",
	"truncate",
	"shrink-0",
	"relative",
	"absolute",
	"inset-0",
	"overflow-hidden",
	"size-thumb",
	"group-hover:bg-toggle-on-hover",
	"group-active:bg-toggle-on-hover",
	"group-hover:bg-wash-hover",
	"group-active:bg-wash-press",
	"group-data-disabled:bg-ink-disabled",
	"not-in-data-disabled:group-hover:bg-wash-hover",
	"not-in-data-disabled:group-active:bg-wash-press",
	"group-not-data-disabled/toggle:group-hover/toggle:bg-wash-hover",
	"group-not-data-disabled/toggle:group-active/toggle:bg-wash-press",
	"group-not-data-disabled/toggle:group-hover/toggle:bg-switch-off-hover",
	"group-not-data-disabled/toggle:group-active/toggle:bg-switch-off-hover",
	"group-not-data-disabled/toggle:group-hover/toggle:bg-toggle-on-hover",
	"group-not-data-disabled/toggle:group-active/toggle:bg-toggle-on-hover",
	"group-hover/toggle:bg-toggle-on-hover",
	"group-active/toggle:bg-toggle-on-hover",
	"group-data-disabled/toggle:bg-fill-disabled",
	"group-data-disabled/toggle:border-edge",
	"group-focus-visible/toggle:outline-2",
	"group-focus-visible/toggle:outline-offset-2",
	"group-focus-visible/toggle:outline-ring",
	"has-focus-visible:outline-2",
	"has-focus-visible:outline-offset-2",
	"has-focus-visible:outline-ring",
	"data-disabled:text-ink-disabled",
	"data-disabled:border-edge",
	"data-disabled:bg-fill-disabled",
	"inline-flex",
	"justify-start",
	"min-h-target",
	"min-w-target",
	"size-target",
	"transition-transform",
	"duration-fast",
	"ease-in-out",
	"data-disabled:bg-ink-disabled",
	// Spinner, Avatar
	"relative",
	"absolute",
	"inset-0",
	"border-current",
	"animate-spin",
	"overflow-hidden",
	"object-cover",
	// Link
	"w-fit",
	"hover:no-underline",
	"active:no-underline",
	"hover:underline",
	"active:underline",
	// Place, Screen, Split
	"min-h-0",
	"overflow-x-clip",
	"overflow-y-auto",
	"pointer-events-none",
	"pointer-events-auto",
	"data-popup-open:bg-wash-press",
	"data-popup-open:text-ink-body",
	"text-danger",
	"overscroll-contain",
	"page-tablet:hidden",
	"page-max-tablet:hidden",
	"page-max-tablet:w-full",
	"page-max-tablet:pb-0",
	"page-max-tablet:border-r-0",
	"page-tablet:group-has-data-split/page:right-auto",
	"page-tablet:group-has-data-split/page:w-list",
	// The Shell's column reads the page's marks: a pushed Screen hides the tab
	// bar, a floating act shows its room under the toasts.
	"group-has-data-screen/column:hidden",
	"group-has-data-act-floats/column:flex",
	// A docked foot names the anchor the toasts' layer stands above.
	"[anchor-name:--docked-foot]",
	"bottom-[anchor(--docked-foot_top,0px)]",
	// A page's head reads its Split's marks: the back act with a record, the
	// Details act with a pane, no head beside a record, the Toolbar leaving
	// with the list.
	"page-max-tablet:group-has-data-record/page:flex",
	"page-max-tablet:group-has-data-record/page:hidden",
	"page-max-wide:group-has-data-pane/page:flex",
	"group-has-[[data-pane][data-beside]]/page:flex",
	"page-max-tablet:group-has-data-beside/page:hidden",
	"page-max-tablet:group-has-data-beside/page:block",
	// A region reads the mark of a Thread filling it: no inset, the log
	// scrolling; the record's head over it stands in the Thread's column.
	"[&:has(>[data-fill])]:p-0",
	"[&:has(>[data-fill])]:gap-0",
	"[&:has(>[data-fill])]:pb-0",
	"[&:has(>[data-fill])]:shrink",
	"[&:has(>[data-fill])]:min-h-0",
	"group-[:has(>[data-fill])]/main:w-full",
	"group-[:has(>[data-fill])]/main:max-w-measure",
	"group-[:has(>[data-fill])]/main:mx-auto",
	"page-wide:hidden",
	"page-max-wide:hidden",
	"border-edge",
	"page-wide:border-l",
	// Section, Group, List, Columns
	"px-inside",
	"tabular-nums",
	"flex",
	"flex-col",
	"min-w-0",
	"items-start",
	"items-center",
	"inline-flex",
	"shrink-0",
	"truncate",
	"text-start",
	"text-end",
	"text-ink-meta",
	"overflow-hidden",
	"overflow-x-auto",
	"-mx-page",
	"grid-cols-1",
	"page-desktop:grid-cols-2",
	// Form, Toolbar, ActionBar
	"page-max-tablet:hidden",
	"flex",
	"flex-col",
	"flex-wrap",
	"items-center",
	"items-end",
	"justify-end",
	"min-w-0",
	"grid",
	"grid-flow-col",
	"touch:w-full",
	"touch:flex",
	"touch:flex-col",
	"touch:items-stretch",
	"touch:flex-wrap",
	// Shell
	"h-dvh",
	"z-(--layer-toasts)",
	"pb-safe",
	"text-left",
	"top-0",
	"left-full",
	"max-w-full",
	"flex-col-reverse",
	// DefinitionRow, ItemHeader
	"relative",
	"after:absolute",
	"after:inset-0",
	"focus-visible:outline-none",
	"focus-visible:after:outline-2",
	"focus-visible:after:-outline-offset-2",
	"focus-visible:after:outline-ring",
	"flex",
	"flex-col",
	"flex-wrap",
	"inline-flex",
	"items-center",
	"justify-center",
	"justify-end",
	"min-w-0",
	"shrink-0",
	"truncate",
	"text-end",
	"text-ink-meta",
	"h-lh",
	"hidden",
	"touch:flex",
	"max-tablet:flex",
	"max-tablet:inline-flex",
	"inline-grid",
	"-mx-inside",
	// EmptyState, QueryBoundary, Banner, PendingBar
	"self-center",
	"text-center",
	"items-start",
	"items-end",
	"self-stretch",
	"justify-center",
	"inline-flex",
	"text-danger",
	"gap-acts",
	"h-lh",
	"overflow-hidden",
	"bottom-0",
	"left-0",
	"touch:flex-col",
	"touch:items-start",
	"touch:items-stretch",
	"touch:gap-pair",
	"touch:self-stretch",
	"touch:text-start",
	// Sheet, Menu, Toast
	"z-(--layer-sheet)",
	"z-(--layer-popover)",
	"relative",
	"absolute",
	"inset-0",
	"flex",
	"flex-col",
	"items-center",
	"items-end",
	"justify-center",
	"justify-end",
	"min-w-0",
	"min-h-0",
	"max-w-full",
	"max-h-full",
	"pb-safe",
	"pt-page",
	"shrink-0",
	"truncate",
	"text-start",
	"text-danger",
	"text-ink-meta",
	"text-ink-disabled",
	"outline-none",
	"overflow-y-auto",
	"overscroll-contain",
	"pointer-events-none",
	"pointer-events-auto",
	"touch:items-center",
	"right-0",
	"w-toast",
	"duration-base",
	"ease-out",
	// Sheet, Menu, Toast motion
	"duration-slow",
	"transition-opacity",
	"transition-[opacity,translate]",
	"transition-[translate,transform,opacity]",
	"[transition-timing-function:var(--ease-in-out),var(--ease-out),var(--ease-out)]",
	"data-starting-style:opacity-0",
	"data-starting-style:translate-x-full",
	"data-starting-style:translate-y-full",
	"data-starting-style:translate-y-pair",
	"data-starting-style:-translate-y-float",
	"data-starting-style:[transform:translateY(var(--spacing-pair))]",
	"data-ending-style:opacity-0",
	"data-ending-style:translate-x-full",
	"data-ending-style:translate-y-full",
	"data-ending-style:duration-base",
	"data-ending-style:duration-fast",
	"data-ending-style:ease-in",
	// ListRow, FormField, SegmentedControl, Picker, OptionList
	"w-0",
	"w-figures",
	"min-h-chip",
	"h-chip",
	"min-w-icon-meta",
	"min-w-figures",
	"shrink-100000000000000",
	"shrink-100000000000000000000",
	"size-control-compact",
	"border-t",
	"pt-float",
	"w-fit",
	"max-h-(--available-height)",
	"-outline-offset-2",
	"h-line-body",
	"max-w-full",
	"gap-pair",
	"pt-pair",
	"relative",
	"absolute",
	"inset-0",
	"flex",
	"inline-flex",
	"flex-col",
	"flex-wrap",
	"items-center",
	"items-start",
	"justify-center",
	"self-center",
	"min-w-0",
	"min-h-0",
	"shrink-0",
	"truncate",
	"text-start",
	"text-ink-meta",
	"text-ink-body",
	"text-ink-disabled",
	"h-lh",
	"rounded-row",
	"touch:rounded-none",
	"outline-none",
	"placeholder:text-ink-meta",
	"outline-2",
	"outline-offset-2",
	"outline-ring",
	"bg-wash-press",
	"overflow-y-auto",
	"overscroll-contain",
	"px-card",
	"pb-card",
	"focus-visible:-outline-offset-2",
	"shrink-10000000",
	"page-max-tablet:flex-wrap",
	"page-max-tablet:basis-0",
	"page-max-tablet:basis-full",
	"page-max-tablet:justify-end",
	"sr-only",
	"page-max-tablet:sr-only",
	// Prose, Code, Diff, ProseDiff, FileRow, Comparison
	"inline-block",
	"whitespace-pre",
	"whitespace-pre-wrap",
	"wrap-anywhere",
	"wrap-break-word",
	"text-pretty",
	"-indent-control-x",
	"border-collapse",
	"focus-visible:outline-2",
	"text-meta",
	"items-baseline",
	"touch:basis-full",
	"touch:sr-only",
	"text-center",
	"text-end",
	"w-full",
	// Message, MessageInput, Thread, Meter, BarChart, QrCode
	"whitespace-nowrap",
	"max-w-4/5",
	"disabled:placeholder:text-ink-disabled",
	"border-edge-hover",
	"col-start-1",
	"row-start-1",
	"invisible",
	"flex-1",
	"self-start",
	// Gate
	"my-auto",
	"touch:my-0",
	// Stages
	"w-icon-meta",
	// Image
	"object-contain",
	"size-full",
	"h-full",
	// Rules
	"col-span-4",
	"items-stretch",
	"self-end",
	// the four columns (term, arrow, term, remove) size to their content or share what is left; no width token names an auto/fr template
	"grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)_auto]",
	"grid-cols-subgrid",
	// Stats
	"page-tablet:basis-0",
	// Canvas
	"outline-1",
	"outline-selected-outline",
	"overflow-visible",
	"text-grid",
	"text-edge-strong",
	"bottom-page",
	"left-page",
	"inset-x-0",
	// Table
	"font-normal",
	"p-0",
	"table-fixed",
	"w-max",
	"z-1",
	"isolate",
	"page-tablet:flex",
	"group-hover/sort:flex",
	"group-focus-visible/sort:flex",
	"group-hover/row:bg-wash-hover",
	"group-hover/row:bg-wash-selected-hover",
	"group-active/row:bg-wash-press",
	"w-row",
	"left-row",
	"min-h-row",
	"min-h-row-2",
	"w-measure-short",
	"w-measure",
];

// SKELETON: a skeleton bar stands at the length of the text it replaces as a
// fraction of its line. The seven are structural, never a token, and accepted
// on a skeleton bar only (a class literal that spells `bg-skeleton`); check
// b5 accepts them there without requiring them.
export const SKELETON_WIDTHS: readonly string[] = [
	"w-1/12",
	"w-1/5",
	"w-1/4",
	"w-1/3",
	"w-1/2",
	"w-2/3",
	"w-3/4",
];
