// The web overlay allowlist: every class the components spell outside a
// matrix cell, other than a state variant over a contract token, spelled out
// as a second opinion. Check b5 asserts it equals the set swept from
// `src/ui/components`, so a component edit that adds or drops an overlay
// class fails until this list moves with it. Each entry is a board string
// less its cell, verbatim from `atoms-overlays.md`.
export const OVERLAYS: readonly string[] = [
	"max-w-measure",
	// Button, IconButton
	"relative",
	"absolute",
	"inset-0",
	"flex",
	"opacity-0",
	"text-ink-disabled",
	"shrink-0",
	"flex-col",
	"items-start",
	"gap-pair",
	// Status, Chip
	"inline-flex",
	"items-center",
	"justify-center",
	"min-w-0",
	"shrink-0",
	"truncate",
	"focus-visible:-outline-offset-2",
	// Input, TextArea, InputOtp
	"flex",
	"flex-col",
	"items-center",
	"justify-center",
	"justify-end",
	"min-w-0",
	"shrink-0",
	"truncate",
	"block",
	"w-full",
	"relative",
	"absolute",
	"inset-0",
	"opacity-0",
	"text-center",
	"outline-none",
	"placeholder:text-ink-meta",
	"bg-fill-disabled",
	"text-ink-disabled",
	"has-focus-visible:outline-2",
	"has-focus-visible:outline-offset-2",
	"has-focus-visible:outline-ring",
	"not-has-[button:focus-visible]:has-focus-visible:outline-2",
	"not-has-[button:focus-visible]:has-focus-visible:outline-offset-2",
	"not-has-[button:focus-visible]:has-focus-visible:outline-ring",
	"field-sizing-content",
	"peer-focus-visible:outline-2",
	"peer-focus-visible:outline-offset-2",
	"peer-focus-visible:outline-ring",
	"gap-pair",
	"gap-inside",
	"not-has-[button:hover]:hover:border-edge-hover",
	// Select
	"flex",
	"flex-col",
	"items-center",
	"min-w-0",
	"truncate",
	"bg-fill-disabled",
	"text-ink-disabled",
	"w-(--anchor-width)",
	"data-popup-open:outline-2",
	"data-popup-open:outline-offset-2",
	"data-popup-open:outline-ring",
	"px-control-x",
	"pt-pair",
	"outline-none",
	"shrink-0",
	"text-ink-body",
	// Slider, Switch, Checkbox
	"flex",
	"flex-col",
	"justify-center",
	"items-center",
	"justify-between",
	"truncate",
	"shrink-0",
	"relative",
	"absolute",
	"inset-0",
	"overflow-hidden",
	"size-thumb",
	"group-hover:bg-toggle-on-hover",
	"group-active:bg-toggle-on-hover",
	"group-data-disabled:bg-ink-disabled",
	"not-in-data-disabled:group-hover:bg-wash-hover",
	"not-in-data-disabled:group-active:bg-wash-press",
	"group-not-aria-disabled/toggle:group-hover/toggle:bg-wash-hover",
	"group-not-aria-disabled/toggle:group-active/toggle:bg-wash-press",
	"group-not-aria-disabled/toggle:group-hover/toggle:bg-switch-off-hover",
	"group-not-aria-disabled/toggle:group-active/toggle:bg-switch-off-hover",
	"group-not-aria-disabled/toggle:group-hover/toggle:bg-toggle-on-hover",
	"group-not-aria-disabled/toggle:group-active/toggle:bg-toggle-on-hover",
	"group-hover/toggle:bg-toggle-on-hover",
	"group-active/toggle:bg-toggle-on-hover",
	"group-aria-disabled/toggle:bg-fill-disabled",
	"group-aria-disabled/toggle:border-edge",
	"group-focus-visible/toggle:outline-2",
	"group-focus-visible/toggle:outline-offset-2",
	"group-focus-visible/toggle:outline-ring",
	"has-focus-visible:outline-2",
	"has-focus-visible:outline-offset-2",
	"has-focus-visible:outline-ring",
	"data-disabled:text-ink-disabled",
	"data-disabled:border-edge",
	"data-disabled:bg-fill-disabled",
	"inline-flex",
	"justify-start",
	"min-h-target",
	"min-w-target",
	"size-target",
	"transition-transform",
	"duration-fast",
	"ease-in-out",
	"data-disabled:bg-ink-disabled",
	// Spinner, Avatar
	"relative",
	"absolute",
	"inset-0",
	"border-current",
	"animate-spin",
	"overflow-hidden",
	"object-cover",
	// Link
	"w-fit",
	"hover:no-underline",
	"active:no-underline",
	"hover:underline",
	"active:underline",
	// Place, Screen, Split
	"min-h-0",
	"overflow-y-auto",
	"pointer-events-none",
	"pointer-events-auto",
	"data-popup-open:bg-wash-press",
	"data-popup-open:text-ink-body",
	"w-popover",
	"gap-rows",
	"text-danger",
	"inset-y-0",
	"right-0",
	"overscroll-contain",
	"page-tablet:hidden",
	"page-max-tablet:hidden",
	"page-max-tablet:w-full",
	"page-max-tablet:pb-0",
	"page-max-tablet:pt-page",
	"page-max-tablet:border-r-0",
	"page-wide:hidden",
	"page-max-wide:hidden",
	// Section, Group, List, Columns
	"flex",
	"flex-col",
	"min-w-0",
	"items-start",
	"items-center",
	"inline-flex",
	"shrink-0",
	"truncate",
	"text-start",
	"text-end",
	"text-ink-meta",
	"overflow-hidden",
	"overflow-x-auto",
	"-mx-page",
	// Form, Toolbar, ActionBar
	"flex",
	"flex-col",
	"flex-wrap",
	"items-center",
	"items-end",
	"justify-end",
	"min-w-0",
	"grid",
	"touch:w-full",
	"touch:flex",
	"touch:flex-col",
	"touch:items-stretch",
	// Shell
	"h-dvh",
	"pb-safe",
	"text-left",
	"border-t",
	"border-edge",
	"pt-float",
	"top-0",
	"left-full",
	"max-w-full",
];

// SKELETON: a skeleton bar stands at the length of the text it replaces as a
// fraction of its line. The five are structural, never a token, and accepted
// on a skeleton bar only (a class literal that spells `bg-skeleton`); check
// b5 accepts them there without requiring them.
export const SKELETON_WIDTHS: readonly string[] = [
	"w-1/4",
	"w-1/3",
	"w-1/2",
	"w-2/3",
	"w-3/4",
];
