// The web overlay allowlist: every class the components spell outside a
// matrix cell, other than a state variant over a contract token, spelled out
// as a second opinion. Check b5 asserts it equals the set swept from
// `src/ui/components`, so a component edit that adds or drops an overlay
// class fails until this list moves with it. Each entry is a board string
// less its cell, verbatim from `atoms-overlays.md`.
export const OVERLAYS: readonly string[] = [
	"max-w-measure",
	// Button, IconButton
	"relative",
	"absolute",
	"inset-0",
	"flex",
	"opacity-0",
	"text-ink-disabled",
	"shrink-0",
	"flex-col",
	"items-start",
	"gap-pair",
	"text-ink-error",
	// Status, Chip
	"inline-flex",
	"items-center",
	"justify-center",
	"min-w-0",
	"shrink-0",
	"truncate",
	"focus-visible:-outline-offset-2",
	// Input, TextArea, InputOtp
	"flex",
	"flex-col",
	"items-center",
	"justify-center",
	"justify-end",
	"min-w-0",
	"shrink-0",
	"truncate",
	"block",
	"w-full",
	"relative",
	"absolute",
	"inset-0",
	"opacity-0",
	"text-center",
	"outline-none",
	"placeholder:text-ink-meta",
	"bg-fill-disabled",
	"text-ink-disabled",
	"has-focus-visible:outline-2",
	"has-focus-visible:outline-offset-2",
	"has-focus-visible:outline-ring",
	"not-has-[button:focus-visible]:has-focus-visible:outline-2",
	"not-has-[button:focus-visible]:has-focus-visible:outline-offset-2",
	"not-has-[button:focus-visible]:has-focus-visible:outline-ring",
	"field-sizing-content",
	"peer-focus-visible:outline-2",
	"peer-focus-visible:outline-offset-2",
	"peer-focus-visible:outline-ring",
	"gap-pair",
	"gap-inside",
	"not-has-[button:hover]:hover:border-edge-hover",
	// Select
	"flex",
	"flex-col",
	"items-center",
	"min-w-0",
	"truncate",
	"bg-fill-disabled",
	"text-ink-disabled",
	"w-(--anchor-width)",
	"data-popup-open:outline-2",
	"data-popup-open:outline-offset-2",
	"data-popup-open:outline-ring",
	"px-control-x",
	"pt-pair",
	"outline-none",
	"shrink-0",
	"text-ink-body",
	// Slider, Switch, Checkbox
	"flex",
	"flex-col",
	"justify-center",
	"items-center",
	"justify-between",
	"truncate",
	"shrink-0",
	"relative",
	"absolute",
	"inset-0",
	"overflow-hidden",
	"size-thumb",
	"group-hover:bg-toggle-on-hover",
	"group-active:bg-toggle-on-hover",
	"group-data-disabled:bg-ink-disabled",
	"not-in-data-disabled:group-hover:bg-wash-hover",
	"not-in-data-disabled:group-active:bg-wash-press",
	"group-not-aria-disabled/toggle:group-hover/toggle:bg-wash-hover",
	"group-not-aria-disabled/toggle:group-active/toggle:bg-wash-press",
	"group-not-aria-disabled/toggle:group-hover/toggle:bg-switch-off-hover",
	"group-not-aria-disabled/toggle:group-active/toggle:bg-switch-off-hover",
	"group-not-aria-disabled/toggle:group-hover/toggle:bg-toggle-on-hover",
	"group-not-aria-disabled/toggle:group-active/toggle:bg-toggle-on-hover",
	"group-hover/toggle:bg-toggle-on-hover",
	"group-active/toggle:bg-toggle-on-hover",
	"group-aria-disabled/toggle:bg-fill-disabled",
	"group-aria-disabled/toggle:border-edge",
	"group-focus-visible/toggle:outline-2",
	"group-focus-visible/toggle:outline-offset-2",
	"group-focus-visible/toggle:outline-ring",
	"has-focus-visible:outline-2",
	"has-focus-visible:outline-offset-2",
	"has-focus-visible:outline-ring",
	"data-disabled:text-ink-disabled",
	"data-disabled:border-edge",
	"data-disabled:bg-fill-disabled",
	"inline-flex",
	"justify-start",
	"min-h-target",
	"min-w-target",
	"size-target",
	"transition-transform",
	"duration-fast",
	"ease-in-out",
	"data-disabled:bg-ink-disabled",
	// Spinner, Avatar
	"relative",
	"absolute",
	"inset-0",
	"border-current",
	"animate-spin",
	"overflow-hidden",
	"object-cover",
	// Link
	"w-fit",
	"hover:no-underline",
	"active:no-underline",
	"hover:underline",
	"active:underline",
];
