import { execFileSync } from "node:child_process";
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

export const STORIES_DIR = path.join(dirname, "..", "stories");
// The showcase's own source, reached through the workspace link.
export const CELLS_FILE = require.resolve(
	"@fcalell/plugin-react-ui/showcase/cells",
);
export const FRAMES_DIR = path.join(path.dirname(CELLS_FILE), "frames");
// ui-core's built roster and variants: a roster edit lands here.
export const UI_CORE_DIST = path.dirname(
	require.resolve("@fcalell/ui-core/roster"),
);

interface RosterComponent {
	layer: string;
	component: string;
	states: string[];
}

const pascal = (word: string) => `${word[0]?.toUpperCase()}${word.slice(1)}`;
const kebab = (name: string) =>
	name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

function list(): RosterComponent[] {
	const out = execFileSync(
		process.execPath,
		[path.join(dirname, "roster-list.ts")],
		{ cwd: dirname, encoding: "utf8" },
	);
	return (JSON.parse(out) as { components: RosterComponent[] }).components;
}

function moduleFor(entry: RosterComponent): string {
	const drawer = kebab(entry.component);
	const drawn = existsSync(path.join(FRAMES_DIR, `${drawer}.tsx`));
	return [
		"// Generated by ../roster.ts from the showcase roster; not edited.",
		...(drawn
			? [
					`import { draw${entry.component} } from "@fcalell/plugin-react-ui/showcase/frames/${drawer}";`,
				]
			: []),
		`import { stateStories } from "../.storybook/state-stories.tsx";`,
		"",
		`const story = stateStories(${JSON.stringify(entry.component)}${drawn ? `, draw${entry.component}` : ""});`,
		"",
		`export default { title: ${JSON.stringify(`${entry.layer}/${entry.component}`)} };`,
		"",
		...entry.states.map(
			(state) =>
				`export const ${pascal(state)} = story(${JSON.stringify(state)});`,
		),
		"",
	].join("\n");
}

// One CSF module per roster component, written only when its text changes so
// an unchanged module is neither re-indexed nor
// re-run by a test watcher.
export function writeStories(): void {
	mkdirSync(STORIES_DIR, { recursive: true });
	const wanted = new Map<string, string>();
	for (const entry of list())
		wanted.set(`${entry.component}.stories.ts`, moduleFor(entry));
	for (const file of readdirSync(STORIES_DIR))
		if (!wanted.has(file)) rmSync(path.join(STORIES_DIR, file));
	for (const [file, source] of wanted) {
		const target = path.join(STORIES_DIR, file);
		if (!existsSync(target) || readFileSync(target, "utf8") !== source)
			writeFileSync(target, source);
	}
}
