import { execFileSync } from "node:child_process";
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

export const STORIES_DIR = path.join(dirname, "..", "stories");
// The showcase's own source, reached through the workspace link.
export const CELLS_FILE = require.resolve(
	"@fcalell/plugin-react-ui/showcase/cells",
);
export const FRAMES_DIR = path.join(path.dirname(CELLS_FILE), "frames");
export const PAGES_FILE = require.resolve(
	"@fcalell/plugin-react-ui/showcase/pages",
);
// ui-core's built roster and variants: a roster edit lands here.
export const UI_CORE_DIST = path.dirname(
	require.resolve("@fcalell/ui-core/roster"),
);

interface RosterComponent {
	layer: string;
	component: string;
	states: string[];
}

interface RosterPage {
	name: string;
	place: string;
	screen?: string;
	record?: string;
}

const pascal = (word: string) => `${word[0]?.toUpperCase()}${word.slice(1)}`;
const camel = (name: string) =>
	name.replace(/-(\w)/g, (_, letter: string) => letter.toUpperCase());
const kebab = (name: string) =>
	name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

interface Listing {
	components: RosterComponent[];
	pages: RosterPage[];
}

function list(): Listing {
	const out = execFileSync(
		process.execPath,
		[path.join(dirname, "roster-list.ts")],
		{ cwd: dirname, encoding: "utf8" },
	);
	return JSON.parse(out) as Listing;
}

function moduleFor(entry: RosterComponent): string {
	const drawer = kebab(entry.component);
	const drawn = existsSync(path.join(FRAMES_DIR, `${drawer}.tsx`));
	return [
		"// Generated by ../roster.ts from the showcase roster; not edited.",
		...(drawn
			? [
					`import { draw${entry.component} } from "@fcalell/plugin-react-ui/showcase/frames/${drawer}";`,
				]
			: []),
		`import { stateStories } from "../.storybook/state-stories.tsx";`,
		"",
		`const story = stateStories(${JSON.stringify(entry.component)}${drawn ? `, draw${entry.component}` : ""});`,
		"",
		`export default { title: ${JSON.stringify(`${entry.layer}/${entry.component}`)} };`,
		"",
		...entry.states.map(
			(state) =>
				`export const ${pascal(state)} = story(${JSON.stringify(state)});`,
		),
		"",
	].join("\n");
}

// One story per page, light and dark: the app's places and the Screen and
// record pushed over them.
function pagesModule(pages: RosterPage[]): string {
	return [
		"// Generated by ../roster.ts from the showcase's pages; not edited.",
		`import { pageStory } from "../.storybook/page-stories.tsx";`,
		"",
		`export default { title: "Pages" };`,
		"",
		...pages.flatMap((page) =>
			(["light", "dark"] as const).map((mode) => {
				const { name, ...here } = page;
				return `export const ${pascal(camel(name))}${pascal(mode)} = pageStory(${JSON.stringify(here)}, ${JSON.stringify(mode)});`;
			}),
		),
		"",
	].join("\n");
}

// One CSF module per roster component and one for the pages, written only
// when its text changes so an unchanged module is neither re-indexed nor
// re-run by a test watcher.
export function writeStories(): void {
	mkdirSync(STORIES_DIR, { recursive: true });
	const wanted = new Map<string, string>();
	const { components, pages } = list();
	for (const entry of components)
		wanted.set(`${entry.component}.stories.ts`, moduleFor(entry));
	wanted.set("Pages.stories.ts", pagesModule(pages));
	for (const file of readdirSync(STORIES_DIR))
		if (!wanted.has(file)) rmSync(path.join(STORIES_DIR, file));
	for (const [file, source] of wanted) {
		const target = path.join(STORIES_DIR, file);
		if (!existsSync(target) || readFileSync(target, "utf8") !== source)
			writeFileSync(target, source);
	}
}
