import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { Plugin, ViteDevServer } from "vite";

const VIRTUAL_CSS = "virtual:fcalell-app-styles.css";
const RESOLVED_CSS = `\0${VIRTUAL_CSS}`;

const VIRTUAL_CLIENT = "virtual:fcalell-api-client";
const RESOLVED_CLIENT = `\0${VIRTUAL_CLIENT}`;

const STACK_DIR = ".stack";

export function appEntryPlugin(): Plugin {
	let projectRoot: string;
	let hasUserEntry: boolean;
	let hasUserCss: boolean;
	let hasIndexHtml: boolean;
	let hasWorker: boolean;

	function detect(root: string): void {
		projectRoot = root;
		hasUserEntry = existsSync(join(root, "src/app/entry.tsx"));
		hasUserCss = existsSync(join(root, "src/app/app.css"));
		hasIndexHtml = existsSync(join(root, "index.html"));
		hasWorker = existsSync(join(root, "src/worker/index.ts"));
	}

	function generateHtml(): string {
		if (hasUserEntry) {
			return `<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	</head>
	<body>
		<div id="root"></div>
		<script type="module" src="/src/app/entry.tsx"></script>
	</body>
</html>`;
		}

		const cssImport = hasUserCss
			? 'import "/src/app/app.css";'
			: `import "${VIRTUAL_CSS}";`;

		return `<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	</head>
	<body>
		<div id="root"></div>
		<script type="module">
${cssImport}
import { createApp } from "@fcalell/ui/app";
createApp();
</script>
	</body>
</html>`;
	}

	function writeApiClientDts(): void {
		if (!hasWorker) return;
		const dtsDir = join(projectRoot, STACK_DIR);
		mkdirSync(dtsDir, { recursive: true });
		writeFileSync(
			join(dtsDir, "api-client.d.ts"),
			`// Generated by @fcalell/vite — do not edit.
declare module "virtual:fcalell-api-client" {
	import type { AppRouter } from "../src/worker/index";
	import type { RouterClient } from "@fcalell/api/client";
	export const api: RouterClient<AppRouter>;
}
`,
		);
	}

	return {
		name: "fcalell:app-entry",
		enforce: "pre",

		config(userConfig) {
			detect(userConfig.root ?? process.cwd());
			writeApiClientDts();

			if (!hasIndexHtml) {
				const stackDir = join(projectRoot, STACK_DIR);
				mkdirSync(stackDir, { recursive: true });
				writeFileSync(join(stackDir, "index.html"), generateHtml());

				return {
					build: {
						rollupOptions: {
							input: join(stackDir, "index.html"),
						},
					},
				};
			}
		},

		configureServer(server: ViteDevServer) {
			if (hasIndexHtml) return;

			// Add middleware BEFORE Vite's internal HTML handling so we
			// intercept `/` and `/index.html` before Vite returns a 404.
			server.middlewares.use(async (req, res, next) => {
				const url = req.url ?? "/";
				if (url !== "/" && url !== "/index.html") return next();

				try {
					const html = generateHtml();
					const transformed = await server.transformIndexHtml(
						"/index.html",
						html,
					);
					res.statusCode = 200;
					res.setHeader("Content-Type", "text/html");
					res.end(transformed);
				} catch (err) {
					next(err);
				}
			});
		},

		// Fix the build output path: Rollup names the emitted HTML after the
		// input key.  When input is `.stack/index.html` the key becomes the
		// relative path from root, which would place the output at
		// `dist/.stack/index.html`.  This hook rewrites it to `dist/index.html`.
		generateBundle(_options, bundle) {
			if (hasIndexHtml) return;
			const stackRel = relative(projectRoot, join(projectRoot, STACK_DIR));
			const wrongName = `${stackRel}/index.html`;
			if (bundle[wrongName]) {
				const chunk = bundle[wrongName];
				delete bundle[wrongName];
				chunk.fileName = "index.html";
				bundle["index.html"] = chunk;
			}
		},

		resolveId(id) {
			if (id === VIRTUAL_CSS) return RESOLVED_CSS;
			if (id === VIRTUAL_CLIENT) return RESOLVED_CLIENT;
			return null;
		},

		load(id) {
			if (id === RESOLVED_CSS) {
				return '@import "tailwindcss";\n@import "@fcalell/ui/globals.css";\n';
			}
			if (id === RESOLVED_CLIENT) {
				return 'import { createClient } from "@fcalell/api/client";\nexport const api = createClient();\n';
			}
			return null;
		},
	};
}
